--------------------------------------------------------
--  Constraints for Table ADT_CLASSES
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."ADT_CLASSES" ADD CONSTRAINT "CTRL_CLASESS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."ADT_CLASSES" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_CLASSES" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_CLASSES" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_CLASSES" MODIFY ("IS_DOCTOR_ORDER" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_CLASSES" MODIFY ("IS_DAYCASE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_CLASSES" MODIFY ("CLASS_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_CLASSES" MODIFY ("DESC_S" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_CLASSES" MODIFY ("DESC_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_CLASSES" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_CLASSES" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_CLASSES" MODIFY ("ID" NOT NULL ENABLE);
