--------------------------------------------------------
--  Constraints for Table ADT_PATIENT_DOCUMENTS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."ADT_PATIENT_DOCUMENTS" ADD CONSTRAINT "ADT_PATIENT_DOCUMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."ADT_PATIENT_DOCUMENTS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PATIENT_DOCUMENTS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PATIENT_DOCUMENTS" MODIFY ("URL" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PATIENT_DOCUMENTS" MODIFY ("DOCUMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PATIENT_DOCUMENTS" MODIFY ("DOCUMENT_CODE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PATIENT_DOCUMENTS" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PATIENT_DOCUMENTS" MODIFY ("ID" NOT NULL ENABLE);
