--------------------------------------------------------
--  Constraints for Table ADT_PATIENTS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."ADT_PATIENTS" ADD CONSTRAINT "ADT_PATIENT_REGISTRATIONS_UNQ" UNIQUE ("FACILITY_ID", "PATIENT_CODE", "ADMISSION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."ADT_PATIENTS" ADD CONSTRAINT "ADT_PATIENT_REGISTRATIONS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."ADT_PATIENTS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PATIENTS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PATIENTS" MODIFY ("IS_HEAD_OF_FAMILY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PATIENTS" MODIFY ("IS_UNKNOWN" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PATIENTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PATIENTS" MODIFY ("IS_DIED" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PATIENTS" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PATIENTS" MODIFY ("LAST_NAME_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PATIENTS" MODIFY ("FIRST_NAME_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PATIENTS" MODIFY ("IS_RESIDENT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PATIENTS" MODIFY ("ADMISSION_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PATIENTS" MODIFY ("PATIENT_CODE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PATIENTS" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PATIENTS" MODIFY ("ID" NOT NULL ENABLE);
