--------------------------------------------------------
--  Constraints for Table ADT_DIAGNOSIS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."ADT_DIAGNOSIS" ADD CONSTRAINT "ADT_DIAGNOSIS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."ADT_DIAGNOSIS" ADD CONSTRAINT "ADT_DIAGNOSIS_UNQ" UNIQUE ("FACILITY_ID", "PATIENT_ID", "ADMISSION_ID", "DIAGNOSIS_TYPE", "DIAGNOSIS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."ADT_DIAGNOSIS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_DIAGNOSIS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_DIAGNOSIS" MODIFY ("DIAGNOSIS_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_DIAGNOSIS" MODIFY ("DIAGNOSIS_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_DIAGNOSIS" MODIFY ("ADMISSION_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_DIAGNOSIS" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_DIAGNOSIS" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_DIAGNOSIS" MODIFY ("ID" NOT NULL ENABLE);
