--------------------------------------------------------
--  Constraints for Table ADT_COMPANION_PERIODS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."ADT_COMPANION_PERIODS" ADD CONSTRAINT "ADT_COMPANION_PERIODS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."ADT_COMPANION_PERIODS" MODIFY ("COMPANION_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_COMPANION_PERIODS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_COMPANION_PERIODS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_COMPANION_PERIODS" MODIFY ("ADMISSION_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_COMPANION_PERIODS" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_COMPANION_PERIODS" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_COMPANION_PERIODS" MODIFY ("TO_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_COMPANION_PERIODS" MODIFY ("FROM_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_COMPANION_PERIODS" MODIFY ("ID" NOT NULL ENABLE);
