--------------------------------------------------------
--  Constraints for Table ADT_PREADMISSION_REQUESTS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."ADT_PREADMISSION_REQUESTS" ADD CONSTRAINT "ADT_PREADMISSION_REQUESTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."ADT_PREADMISSION_REQUESTS" MODIFY ("SECTION_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PREADMISSION_REQUESTS" MODIFY ("IS_EMERGENCY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PREADMISSION_REQUESTS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PREADMISSION_REQUESTS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PREADMISSION_REQUESTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PREADMISSION_REQUESTS" MODIFY ("ENTRY_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PREADMISSION_REQUESTS" MODIFY ("IS_DAY_CASE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PREADMISSION_REQUESTS" MODIFY ("IS_ISOLATED" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PREADMISSION_REQUESTS" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PREADMISSION_REQUESTS" MODIFY ("REQUESTED_SECTION" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PREADMISSION_REQUESTS" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_PREADMISSION_REQUESTS" MODIFY ("ID" NOT NULL ENABLE);
