--------------------------------------------------------
--  Constraints for Table ADT_TRANSFERS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."ADT_TRANSFERS" ADD CONSTRAINT "ADT_TRANSFERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."ADT_TRANSFERS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_TRANSFERS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_TRANSFERS" MODIFY ("ENTRY_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_TRANSFERS" MODIFY ("ACTUAL_CLASS_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_TRANSFERS" MODIFY ("REQUESTED_CLASS_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_TRANSFERS" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_TRANSFERS" MODIFY ("IS_ADDITIONAL_BED" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_TRANSFERS" MODIFY ("BED_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_TRANSFERS" MODIFY ("ROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_TRANSFERS" MODIFY ("SECTION_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_TRANSFERS" MODIFY ("HAS_COMPANION" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_TRANSFERS" MODIFY ("ADMISSION_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_TRANSFERS" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_TRANSFERS" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_TRANSFERS" MODIFY ("ID" NOT NULL ENABLE);
