--------------------------------------------------------
--  Constraints for Table ADT_ADMISSIONS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."ADT_ADMISSIONS" ADD CONSTRAINT "ADT_ADMISSIONS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."ADT_ADMISSIONS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_ADMISSIONS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_ADMISSIONS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_ADMISSIONS" MODIFY ("BED_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_ADMISSIONS" MODIFY ("ROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_ADMISSIONS" MODIFY ("SECTION_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_ADMISSIONS" MODIFY ("DOCTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_ADMISSIONS" MODIFY ("ADMISSION_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_ADMISSIONS" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_ADMISSIONS" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_ADMISSIONS" MODIFY ("ID" NOT NULL ENABLE);
