--------------------------------------------------------
--  Constraints for Table ADT_COMPANIONS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."ADT_COMPANIONS" ADD CONSTRAINT "ADT_COMPANIONS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."ADT_COMPANIONS" MODIFY ("IS_ADDITIONAL_BED" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_COMPANIONS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_COMPANIONS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_COMPANIONS" MODIFY ("IS_MEAL_PROVIDED" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_COMPANIONS" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_COMPANIONS" MODIFY ("LAST_NAME_S" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_COMPANIONS" MODIFY ("FIRST_NAME_S" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_COMPANIONS" MODIFY ("LAST_NAME_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_COMPANIONS" MODIFY ("FIRST_NAME_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_COMPANIONS" MODIFY ("ADMISSION_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_COMPANIONS" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_COMPANIONS" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ADT_COMPANIONS" MODIFY ("ID" NOT NULL ENABLE);
