--------------------------------------------------------
--  Constraints for Table CTR_LONG_TEXT
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."CTR_LONG_TEXT" ADD CONSTRAINT "CTR_LONG_TEXT_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "HISRHAMZEH"."CTRL_LONG_TEXT_PK" ON "HISRHAMZEH"."CTR_LONG_TEXT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "HISRHAMZEH"."CTR_LONG_TEXT" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_LONG_TEXT" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_LONG_TEXT" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_LONG_TEXT" MODIFY ("UPDT_CNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_LONG_TEXT" MODIFY ("PARENT_ENTITY_NAME" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_LONG_TEXT" MODIFY ("PARENT_ENTITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_LONG_TEXT" MODIFY ("ACTIVE_IND" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_LONG_TEXT" MODIFY ("ID" NOT NULL ENABLE);
