--------------------------------------------------------
--  Constraints for Table CTR_BILL_TYPES
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."CTR_BILL_TYPES" ADD CONSTRAINT "CTR_BILL_TYPES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."CTR_BILL_TYPES" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_BILL_TYPES" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_BILL_TYPES" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_BILL_TYPES" MODIFY ("TYPE_DESC_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_BILL_TYPES" MODIFY ("ID" NOT NULL ENABLE);
