--------------------------------------------------------
--  Constraints for Table CTR_STAFF
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."CTR_STAFF" ADD CONSTRAINT "CTR_STAFF_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "HISRHAMZEH"."CTRL_STAFF_PK" ON "HISRHAMZEH"."CTR_STAFF" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "HISRHAMZEH"."CTR_STAFF" ADD CONSTRAINT "CTR_STAFF_UNQ" UNIQUE ("FACILITY_ID", "STAFF_CODE")
  USING INDEX (CREATE UNIQUE INDEX "HISRHAMZEH"."CTRL_STAFF_UNQ" ON "HISRHAMZEH"."CTR_STAFF" ("FACILITY_ID", "STAFF_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "HISRHAMZEH"."CTR_STAFF" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_STAFF" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_STAFF" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_STAFF" MODIFY ("IS_CITIZENSHIP" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_STAFF" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_STAFF" MODIFY ("FIRST_NAME_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_STAFF" MODIFY ("LAST_NAME_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_STAFF" MODIFY ("STAFF_CODE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_STAFF" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_STAFF" MODIFY ("ID" NOT NULL ENABLE);
