--------------------------------------------------------
--  Constraints for Table CTR_USER_SECTIONS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."CTR_USER_SECTIONS" ADD CONSTRAINT "CTRL_USER_SECTIONS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."CTR_USER_SECTIONS" MODIFY ("SECTION_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_USER_SECTIONS" MODIFY ("USER_ID" NOT NULL ENABLE);
