--------------------------------------------------------
--  Constraints for Table CTR_ORDER_CATALOG_ITEMS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."CTR_ORDER_CATALOG_ITEMS" ADD CONSTRAINT "CTR_ORDER_CATALOG_ITEMS_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "HISRHAMZEH"."CTRL_ORDER_CATALOG_ITEMS_PK" ON "HISRHAMZEH"."CTR_ORDER_CATALOG_ITEMS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "HISRHAMZEH"."CTR_ORDER_CATALOG_ITEMS" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_ORDER_CATALOG_ITEMS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_ORDER_CATALOG_ITEMS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_ORDER_CATALOG_ITEMS" MODIFY ("OE_FORMAT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_ORDER_CATALOG_ITEMS" MODIFY ("MULTUM_DRUG_IDENTIFIER" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_ORDER_CATALOG_ITEMS" MODIFY ("UPDT_CNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_ORDER_CATALOG_ITEMS" MODIFY ("SYNONYM_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_ORDER_CATALOG_ITEMS" MODIFY ("ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_ORDER_CATALOG_ITEMS" MODIFY ("CATALOG_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_ORDER_CATALOG_ITEMS" MODIFY ("ID" NOT NULL ENABLE);
