--------------------------------------------------------
--  Constraints for Table CTR_USEROLD
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."CTR_USEROLD" ADD CONSTRAINT "CTR_USEROLD_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."CTR_USEROLD" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_USEROLD" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_USEROLD" MODIFY ("CHANGE_PASS_NEXT_LOGIN" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_USEROLD" MODIFY ("CANT_CHANGE_PASS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_USEROLD" MODIFY ("PASSWORD_NEVER_EXPIRE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_USEROLD" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_USEROLD" MODIFY ("FULLNAME" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_USEROLD" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_USEROLD" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_USEROLD" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_USEROLD" MODIFY ("ID" NOT NULL ENABLE);
