--------------------------------------------------------
--  Constraints for Table CTR_BILL_TYPE_SERIALS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."CTR_BILL_TYPE_SERIALS" ADD CONSTRAINT "CTR_BILL_TYPE_SERIALS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."CTR_BILL_TYPE_SERIALS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_BILL_TYPE_SERIALS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_BILL_TYPE_SERIALS" MODIFY ("SERIAL_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_BILL_TYPE_SERIALS" MODIFY ("TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_BILL_TYPE_SERIALS" MODIFY ("ID" NOT NULL ENABLE);
