--------------------------------------------------------
--  Constraints for Table CTR_CODE_VALUE
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."CTR_CODE_VALUE" ADD CONSTRAINT "CTR_CODE_VALUE_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "HISRHAMZEH"."CTRL_CODE_VALUE_PK" ON "HISRHAMZEH"."CTR_CODE_VALUE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "HISRHAMZEH"."CTR_CODE_VALUE" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_CODE_VALUE" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_CODE_VALUE" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_CODE_VALUE" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_CODE_VALUE" MODIFY ("UPDT_CNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_CODE_VALUE" MODIFY ("INACTIVE_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_CODE_VALUE" MODIFY ("END_EFFECTIVE_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_CODE_VALUE" MODIFY ("CODE_VALUE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_CODE_VALUE" MODIFY ("CODE_SET" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_CODE_VALUE" MODIFY ("BEGIN_EFFECTIVE_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_CODE_VALUE" MODIFY ("ACTIVE_IND" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_CODE_VALUE" MODIFY ("ID" NOT NULL ENABLE);
