--------------------------------------------------------
--  Constraints for Table CTR_ORG_SECTIONS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."CTR_ORG_SECTIONS" ADD CONSTRAINT "CTR_ORG_SECTIONS_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "HISRHAMZEH"."CTRL_ORG_SECTIONS_PK" ON "HISRHAMZEH"."CTR_ORG_SECTIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "HISRHAMZEH"."CTR_ORG_SECTIONS" ADD CONSTRAINT "CTR_ORG_SECTIONS_UNQ" UNIQUE ("FACILITY_ID", "CODE")
  USING INDEX (CREATE UNIQUE INDEX "HISRHAMZEH"."CTRL_ORG_SECTIONS_UNQ" ON "HISRHAMZEH"."CTR_ORG_SECTIONS" ("FACILITY_ID", "CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "HISRHAMZEH"."CTR_ORG_SECTIONS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_ORG_SECTIONS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_ORG_SECTIONS" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_ORG_SECTIONS" MODIFY ("IS_LEAF" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_ORG_SECTIONS" MODIFY ("DESC_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_ORG_SECTIONS" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_ORG_SECTIONS" MODIFY ("ID" NOT NULL ENABLE);
