--------------------------------------------------------
--  Constraints for Table CTR_DOCUMENTS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."CTR_DOCUMENTS" ADD CONSTRAINT "CTR_DOCUMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "HISRHAMZEH"."CTRL_DOCUMENTS_PK" ON "HISRHAMZEH"."CTR_DOCUMENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "HISRHAMZEH"."CTR_DOCUMENTS" ADD CONSTRAINT "CTR_DOCUMENTS_UNQ" UNIQUE ("FACILITY_ID", "CODE")
  USING INDEX (CREATE UNIQUE INDEX "HISRHAMZEH"."CTRL_DOCUMENTS_UNQ" ON "HISRHAMZEH"."CTR_DOCUMENTS" ("FACILITY_ID", "CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "HISRHAMZEH"."CTR_DOCUMENTS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_DOCUMENTS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_DOCUMENTS" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_DOCUMENTS" MODIFY ("DESC_S" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_DOCUMENTS" MODIFY ("DESC_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_DOCUMENTS" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_DOCUMENTS" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
