--------------------------------------------------------
--  Constraints for Table CTR_PATIENT_TYPES
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."CTR_PATIENT_TYPES" ADD CONSTRAINT "CTR_PATIENT_TYPES_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "HISRHAMZEH"."CTRL_PATIENT_TYPES_PK" ON "HISRHAMZEH"."CTR_PATIENT_TYPES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "HISRHAMZEH"."CTR_PATIENT_TYPES" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_PATIENT_TYPES" MODIFY ("DESC_S" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_PATIENT_TYPES" MODIFY ("DESC_P" NOT NULL ENABLE);
