--------------------------------------------------------
--  Constraints for Table CTR_BILL_ELEMENTS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."CTR_BILL_ELEMENTS" ADD CONSTRAINT "CTR_BILL_ELEMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."CTR_BILL_ELEMENTS" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_BILL_ELEMENTS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_BILL_ELEMENTS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_BILL_ELEMENTS" MODIFY ("IS_DISCHARGE_PRESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_BILL_ELEMENTS" MODIFY ("IS_LEAF" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_BILL_ELEMENTS" MODIFY ("ELEMENT_DESC_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_BILL_ELEMENTS" MODIFY ("ID" NOT NULL ENABLE);
