--------------------------------------------------------
--  Constraints for Table CTR_FACILITIES
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."CTR_FACILITIES" ADD CONSTRAINT "CTR_FACILITY_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "HISRHAMZEH"."CTRL_FACILITY_DEFINTIONS_PK" ON "HISRHAMZEH"."CTR_FACILITIES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "HISRHAMZEH"."CTR_FACILITIES" ADD CONSTRAINT "CTR_FACILITY_UNQ" UNIQUE ("CODE")
  USING INDEX (CREATE UNIQUE INDEX "HISRHAMZEH"."CTRL_FACILITY_DEFINTIONS_UNQ" ON "HISRHAMZEH"."CTR_FACILITIES" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "HISRHAMZEH"."CTR_FACILITIES" MODIFY ("COUNTRY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_FACILITIES" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_FACILITIES" MODIFY ("PARENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_FACILITIES" MODIFY ("IS_LEAF" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_FACILITIES" MODIFY ("DESC_S" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_FACILITIES" MODIFY ("DESC_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_FACILITIES" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_FACILITIES" MODIFY ("ID" NOT NULL ENABLE);
