--------------------------------------------------------
--  Constraints for Table CTR_MENUS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."CTR_MENUS" ADD CONSTRAINT "CTR_MENUS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."CTR_MENUS" MODIFY ("IS_PAGE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_MENUS" MODIFY ("NODE_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_MENUS" MODIFY ("NODE_NAME_S" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_MENUS" MODIFY ("NODE_NAME_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_MENUS" MODIFY ("PARENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_MENUS" MODIFY ("ID" NOT NULL ENABLE);
