--------------------------------------------------------
--  Constraints for Table CTR_CONSULTATIONS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."CTR_CONSULTATIONS" ADD CONSTRAINT "CTR_CONSULTATIONS_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "HISRHAMZEH"."CTRL_CONSULTATIONS_PK" ON "HISRHAMZEH"."CTR_CONSULTATIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "HISRHAMZEH"."CTR_CONSULTATIONS" ADD CONSTRAINT "CTR_CONSULTATIONS_UNQ" UNIQUE ("FACILITY_ID", "CONSULTATION_CODE")
  USING INDEX (CREATE UNIQUE INDEX "HISRHAMZEH"."CTRL_CONSULTATIONS_UNQ" ON "HISRHAMZEH"."CTR_CONSULTATIONS" ("FACILITY_ID", "CONSULTATION_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "HISRHAMZEH"."CTR_CONSULTATIONS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_CONSULTATIONS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_CONSULTATIONS" MODIFY ("CONSULTATION_DESC_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_CONSULTATIONS" MODIFY ("CONSULTATION_CODE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_CONSULTATIONS" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_CONSULTATIONS" MODIFY ("ID" NOT NULL ENABLE);
