--------------------------------------------------------
--  Constraints for Table CTR_DIAGNOSIS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."CTR_DIAGNOSIS" ADD CONSTRAINT "CTR_DIAGNOSIS_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "HISRHAMZEH"."CTRL_DIAGNOSIS_PK" ON "HISRHAMZEH"."CTR_DIAGNOSIS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "HISRHAMZEH"."CTR_DIAGNOSIS" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_DIAGNOSIS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_DIAGNOSIS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_DIAGNOSIS" MODIFY ("IS_LEAF" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_DIAGNOSIS" MODIFY ("DESC_S" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_DIAGNOSIS" MODIFY ("DESC_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."CTR_DIAGNOSIS" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
