--------------------------------------------------------
--  Constraints for Table INS_GUARANTOR_POLICIES
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_POLICIES" ADD CONSTRAINT "INS_GUARANTOR_POLICIES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_POLICIES" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_POLICIES" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_POLICIES" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_POLICIES" MODIFY ("DISCOUNT_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_POLICIES" MODIFY ("CONTRACT_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_POLICIES" MODIFY ("DEALING_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_POLICIES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_POLICIES" MODIFY ("PRICING_LIST_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_POLICIES" MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_POLICIES" MODIFY ("BEGIN_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_POLICIES" MODIFY ("POLICY_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_POLICIES" MODIFY ("CONTRACT_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_POLICIES" MODIFY ("GUARANTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_POLICIES" MODIFY ("ID" NOT NULL ENABLE);
