--------------------------------------------------------
--  Constraints for Table INS_GUARANTOR_SERVICES
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_SERVICES" ADD CONSTRAINT "INS_GUARANTOR_SERVICES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_SERVICES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_SERVICES" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_SERVICES" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_SERVICES" MODIFY ("GUARANTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_SERVICES" MODIFY ("ITEM_CODE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_SERVICES" MODIFY ("ITEM_DESC" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_SERVICES" MODIFY ("ITEM_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_SERVICES" MODIFY ("ID" NOT NULL ENABLE);
