--------------------------------------------------------
--  Constraints for Table INS_EXCLUDED_LIMIT_DTL
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_LIMIT_DTL" ADD CONSTRAINT "INS_EXCLUDEDLIMIT_DTL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_LIMIT_DTL" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_LIMIT_DTL" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_LIMIT_DTL" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_LIMIT_DTL" MODIFY ("SUB_EXCLUDE_ITEM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_LIMIT_DTL" MODIFY ("SUB_ITEM_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_LIMIT_DTL" MODIFY ("ITEM_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_LIMIT_DTL" MODIFY ("PAGE_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_LIMIT_DTL" MODIFY ("GUARANTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_LIMIT_DTL" MODIFY ("ID" NOT NULL ENABLE);
