--------------------------------------------------------
--  Constraints for Table INS_PKGCOVERAGE_SERVICES
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."INS_PKGCOVERAGE_SERVICES" ADD CONSTRAINT "INS_PKGCOVERAGE_SERVICES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."INS_PKGCOVERAGE_SERVICES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PKGCOVERAGE_SERVICES" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PKGCOVERAGE_SERVICES" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PKGCOVERAGE_SERVICES" MODIFY ("IS_DISCHARGE_PRESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PKGCOVERAGE_SERVICES" MODIFY ("DISCOUNT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PKGCOVERAGE_SERVICES" MODIFY ("ITEM_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PKGCOVERAGE_SERVICES" MODIFY ("PKG_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PKGCOVERAGE_SERVICES" MODIFY ("ID" NOT NULL ENABLE);
