--------------------------------------------------------
--  Constraints for Table INS_PACKAGES
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."INS_PACKAGES" ADD CONSTRAINT "INS_PACKAGES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGES" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGES" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGES" MODIFY ("IS_LONG_TERM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGES" MODIFY ("COVERAGE_ON" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGES" MODIFY ("INITIAL_PRICE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGES" MODIFY ("PACKAGE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGES" MODIFY ("PERIOD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGES" MODIFY ("GUARANTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGES" MODIFY ("ITEM_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGES" MODIFY ("PKG_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGES" MODIFY ("ID" NOT NULL ENABLE);
