--------------------------------------------------------
--  Constraints for Table INS_EXCLUDED_LIMITS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_LIMITS" ADD CONSTRAINT "INS_EXCLUDED_LIMITS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_LIMITS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_LIMITS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_LIMITS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_LIMITS" MODIFY ("NOT_EXCLUDED" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_LIMITS" MODIFY ("PERIOD_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_LIMITS" MODIFY ("PATIENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_LIMITS" MODIFY ("ITEM_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_LIMITS" MODIFY ("GUARANTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_LIMITS" MODIFY ("SERIAL_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_LIMITS" MODIFY ("ID" NOT NULL ENABLE);
