--------------------------------------------------------
--  Constraints for Table INS_PACKAGE_DESCRIPTIONS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."INS_PACKAGE_DESCRIPTIONS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGE_DESCRIPTIONS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGE_DESCRIPTIONS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGE_DESCRIPTIONS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGE_DESCRIPTIONS" MODIFY ("PCKG_DESCR" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGE_DESCRIPTIONS" MODIFY ("PCKG_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGE_DESCRIPTIONS" MODIFY ("ID" NOT NULL ENABLE);
