--------------------------------------------------------
--  Constraints for Table INS_LIMIT_CHARGES
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."INS_LIMIT_CHARGES" ADD CONSTRAINT "INS_LIMIT_CHARGES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."INS_LIMIT_CHARGES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_LIMIT_CHARGES" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_LIMIT_CHARGES" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_LIMIT_CHARGES" MODIFY ("PATIENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_LIMIT_CHARGES" MODIFY ("LIMIT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_LIMIT_CHARGES" MODIFY ("LIMIT_CHARGE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_LIMIT_CHARGES" MODIFY ("ITEM_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_LIMIT_CHARGES" MODIFY ("GUARANTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_LIMIT_CHARGES" MODIFY ("SERIAL_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_LIMIT_CHARGES" MODIFY ("ID" NOT NULL ENABLE);
