--------------------------------------------------------
--  Constraints for Table INS_CASH_LIMITS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."INS_CASH_LIMITS" ADD CONSTRAINT "INS_CASH_LIMITS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."INS_CASH_LIMITS" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_CASH_LIMITS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_CASH_LIMITS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_CASH_LIMITS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_CASH_LIMITS" MODIFY ("SECTION_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_CASH_LIMITS" MODIFY ("ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_CASH_LIMITS" MODIFY ("LIMIT_VALUE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_CASH_LIMITS" MODIFY ("NEEDS_APPROVAL" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_CASH_LIMITS" MODIFY ("LIMIT_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_CASH_LIMITS" MODIFY ("PATIENT_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_CASH_LIMITS" MODIFY ("GUARANTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_CASH_LIMITS" MODIFY ("ID" NOT NULL ENABLE);
