--------------------------------------------------------
--  Constraints for Table INS_EXCLUDED_DIAGNOSIS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_DIAGNOSIS" ADD CONSTRAINT "INS_EXCLUDED_DIAGNOSIS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_DIAGNOSIS" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_DIAGNOSIS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_DIAGNOSIS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_DIAGNOSIS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_DIAGNOSIS" MODIFY ("NOT_EXCLUDED" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_DIAGNOSIS" MODIFY ("PATIENT_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_DIAGNOSIS" MODIFY ("DIAGNOSIS_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_DIAGNOSIS" MODIFY ("GUARANTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_DIAGNOSIS" MODIFY ("ID" NOT NULL ENABLE);
