--------------------------------------------------------
--  Constraints for Table INS_GUARANTOR_CONTRACTS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_CONTRACTS" ADD CONSTRAINT "INS_GUARANTOR_CONTRACTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_CONTRACTS" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_CONTRACTS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_CONTRACTS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_CONTRACTS" MODIFY ("FOLLOW_UP_SESSION" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_CONTRACTS" MODIFY ("DISCOUNT_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_CONTRACTS" MODIFY ("ACCOMMODATION_CLASS_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_CONTRACTS" MODIFY ("OUT_BENEFICIARY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_CONTRACTS" MODIFY ("IN_BENEFICIARY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_CONTRACTS" MODIFY ("OUT_SUBSCRIBER" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_CONTRACTS" MODIFY ("IN_SUBSCRIBER" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_CONTRACTS" MODIFY ("IS_AUTO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_CONTRACTS" MODIFY ("CLASS_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_CONTRACTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_CONTRACTS" MODIFY ("IS_CHRONIC_COVERED" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_CONTRACTS" MODIFY ("IS_PREEXIST_COVERED" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_CONTRACTS" MODIFY ("CONTRACT_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_CONTRACTS" MODIFY ("GUARANTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_CONTRACTS" MODIFY ("ID" NOT NULL ENABLE);
