--------------------------------------------------------
--  Constraints for Table INS_GUARANTOR_VALIDLISTS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_VALIDLISTS" ADD CONSTRAINT "INS_GUARANTOR_VALIDLISTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_VALIDLISTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_VALIDLISTS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_VALIDLISTS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_VALIDLISTS" MODIFY ("VALIDLIST_SERIAL" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_VALIDLISTS" MODIFY ("CLASS_CODE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_VALIDLISTS" MODIFY ("IS_BLACK_LIST" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_VALIDLISTS" MODIFY ("SUBSCRIBER_NAME" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_VALIDLISTS" MODIFY ("SUBSCRIBER_CODE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_VALIDLISTS" MODIFY ("GUARANTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTOR_VALIDLISTS" MODIFY ("ID" NOT NULL ENABLE);
