--------------------------------------------------------
--  Constraints for Table INS_PREAPPROVALS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."INS_PREAPPROVALS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."INS_PREAPPROVALS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PREAPPROVALS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PREAPPROVALS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PREAPPROVALS" MODIFY ("AUTO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PREAPPROVALS" MODIFY ("PATIENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PREAPPROVALS" MODIFY ("SECTION_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PREAPPROVALS" MODIFY ("GUARANTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PREAPPROVALS" MODIFY ("SERIAL_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PREAPPROVALS" MODIFY ("ID" NOT NULL ENABLE);
