--------------------------------------------------------
--  Constraints for Table INS_EXCLUDED_SECTIONS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_SECTIONS" ADD CONSTRAINT "INS_EXCLUDED_SECTIONS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_SECTIONS" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_SECTIONS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_SECTIONS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_SECTIONS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_SECTIONS" MODIFY ("NOT_EXCLUDED" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_SECTIONS" MODIFY ("PATIENT_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_SECTIONS" MODIFY ("SECTION_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_SECTIONS" MODIFY ("GUARANTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_EXCLUDED_SECTIONS" MODIFY ("ID" NOT NULL ENABLE);
