--------------------------------------------------------
--  Constraints for Table INS_GUARANTORS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."INS_GUARANTORS" ADD CONSTRAINT "NIS_GUARANTORS_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "HISRHAMZEH"."BILL_GUARANTORS_PK" ON "HISRHAMZEH"."INS_GUARANTORS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTORS" ADD CONSTRAINT "NIS_GUARANTORS_UNQ" UNIQUE ("FACILITY_ID", "CODE")
  USING INDEX (CREATE UNIQUE INDEX "HISRHAMZEH"."BILL_GUARANTORS_UNQ" ON "HISRHAMZEH"."INS_GUARANTORS" ("FACILITY_ID", "CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTORS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTORS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTORS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTORS" MODIFY ("IS_LEAF" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTORS" MODIFY ("DESC_S" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTORS" MODIFY ("DESC_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTORS" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_GUARANTORS" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
