--------------------------------------------------------
--  Constraints for Table INS_PACKAGETEMPLATE_DTL
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."INS_PACKAGETEMPLATE_DTL" ADD CONSTRAINT "INS_PACKAGETEMPLATE_DTL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGETEMPLATE_DTL" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGETEMPLATE_DTL" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGETEMPLATE_DTL" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGETEMPLATE_DTL" MODIFY ("TEMPLATE_CODE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGETEMPLATE_DTL" MODIFY ("PKG_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGETEMPLATE_DTL" MODIFY ("ID" NOT NULL ENABLE);
