--------------------------------------------------------
--  Constraints for Table INS_PREAPPROVAL_DIAGNOSIS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."INS_PREAPPROVAL_DIAGNOSIS" ADD CONSTRAINT "INS_PREAPPROVAL_DIAGNOSIS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."INS_PREAPPROVAL_DIAGNOSIS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PREAPPROVAL_DIAGNOSIS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PREAPPROVAL_DIAGNOSIS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PREAPPROVAL_DIAGNOSIS" MODIFY ("IS_AUTOAPPROVAL_SENT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PREAPPROVAL_DIAGNOSIS" MODIFY ("AUTO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PREAPPROVAL_DIAGNOSIS" MODIFY ("ITEM_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PREAPPROVAL_DIAGNOSIS" MODIFY ("SERIAL_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PREAPPROVAL_DIAGNOSIS" MODIFY ("ID" NOT NULL ENABLE);
