--------------------------------------------------------
--  Constraints for Table INS_PACKAGE_TEMPLATES
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."INS_PACKAGE_TEMPLATES" ADD CONSTRAINT "INS_PACKAGE_TEMPLATES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGE_TEMPLATES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGE_TEMPLATES" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGE_TEMPLATES" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGE_TEMPLATES" MODIFY ("TEMPLATE_DESC" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGE_TEMPLATES" MODIFY ("TEMPLATE_CODE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."INS_PACKAGE_TEMPLATES" MODIFY ("ID" NOT NULL ENABLE);
