--------------------------------------------------------
--  Constraints for Table LAB_INVESTIGATION_TAT
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."LAB_INVESTIGATION_TAT" ADD CONSTRAINT "LAB_INVESTIGATION_TAT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."LAB_INVESTIGATION_TAT" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_INVESTIGATION_TAT" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_INVESTIGATION_TAT" MODIFY ("INV_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_INVESTIGATION_TAT" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_INVESTIGATION_TAT" MODIFY ("TAT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_INVESTIGATION_TAT" MODIFY ("ID" NOT NULL ENABLE);
