--------------------------------------------------------
--  Constraints for Table LAB_CONTAINER_TYPE
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."LAB_CONTAINER_TYPE" ADD CONSTRAINT "LAB_CONTAINER_TYPE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."LAB_CONTAINER_TYPE" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_CONTAINER_TYPE" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_CONTAINER_TYPE" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_CONTAINER_TYPE" MODIFY ("DESC_S" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_CONTAINER_TYPE" MODIFY ("VOLUME" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_CONTAINER_TYPE" MODIFY ("VOLUME_UNIT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_CONTAINER_TYPE" MODIFY ("DISPLAY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_CONTAINER_TYPE" MODIFY ("DESC_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_CONTAINER_TYPE" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_CONTAINER_TYPE" MODIFY ("ID" NOT NULL ENABLE);
