--------------------------------------------------------
--  Constraints for Table LAB_DATA_MAP
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."LAB_DATA_MAP" ADD CONSTRAINT "LAB_DATA_MAP_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."LAB_DATA_MAP" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_DATA_MAP" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_DATA_MAP" MODIFY ("DT_PAR_SEQUENCE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_DATA_MAP" MODIFY ("DT_PAR_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_DATA_MAP" MODIFY ("DT_INV_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_DATA_MAP" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_DATA_MAP" MODIFY ("ID" NOT NULL ENABLE);
