--------------------------------------------------------
--  Constraints for Table LAB_ACC_PART_SETUP
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."LAB_ACC_PART_SETUP" ADD CONSTRAINT "LAB_ACC_PART_SETUP_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."LAB_ACC_PART_SETUP" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ACC_PART_SETUP" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ACC_PART_SETUP" MODIFY ("ACC_PART" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ACC_PART_SETUP" MODIFY ("ACC_PART_TYPE_LGC" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ACC_PART_SETUP" MODIFY ("ACC_PART_SEQUENCE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ACC_PART_SETUP" MODIFY ("ACC_CLASS_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ACC_PART_SETUP" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ACC_PART_SETUP" MODIFY ("ID" NOT NULL ENABLE);
