--------------------------------------------------------
--  Constraints for Table LAB_ORDER_ACCESSION
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."LAB_ORDER_ACCESSION" ADD CONSTRAINT "LAB_ORDER_ACCESSION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."LAB_ORDER_ACCESSION" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ORDER_ACCESSION" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ORDER_ACCESSION" MODIFY ("INV_SECTION_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ORDER_ACCESSION" MODIFY ("INV_SECTION_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ORDER_ACCESSION" MODIFY ("ACCESSION" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ORDER_ACCESSION" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ORDER_ACCESSION" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ORDER_ACCESSION" MODIFY ("ID" NOT NULL ENABLE);
