--------------------------------------------------------
--  Constraints for Table ORD_ORDERS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" ADD CONSTRAINT "ORD_ORDERS_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("MODIFIED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("UPDT_CNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("CREATE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("ORDER_COMPLETE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("ORDER_COMPLETE_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("ORDER_CANCEL_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("ORDER_CANCEL_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("ORDER_CANCEL_REASON_LGC" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("ORDER_CS_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("ORDER_END_EFFICTIVE_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("ORDER_START_EFFICTIVE_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("ORDER_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("PRIORITY_LGC" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("INV_SECTION_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("STOP_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("PRN_IND" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("PERSON_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("ORDER_STATUS_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("ORDER_COMMENT_IND" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("OE_FORMAT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("MED_ORDER_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("IV_IND" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("FREQUENCY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("ENCNTR_FINANCIAL_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("ENCOUNTER_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("CONTRIBUTOR_SYSTEM_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("CATALOG_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("CATALOG_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("ACTIVITY_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDERS" MODIFY ("ACTIVE_IND" NOT NULL ENABLE);
