--------------------------------------------------------
--  Constraints for Table OT_HEADER
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."OT_HEADER" ADD CONSTRAINT "OT_HDR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."OT_HEADER" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_HEADER" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_HEADER" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_HEADER" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_HEADER" MODIFY ("OPERATION_CODE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_HEADER" MODIFY ("ANAESTHETIST_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_HEADER" MODIFY ("SPECIALITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_HEADER" MODIFY ("SURGEON_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_HEADER" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_HEADER" MODIFY ("ID" NOT NULL ENABLE);
