--------------------------------------------------------
--  Constraints for Table OT_OPERATION
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."OT_OPERATION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."OT_OPERATION" ADD CONSTRAINT "OT_OPERATION_U01" UNIQUE ("DESC_P")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."OT_OPERATION" ADD CONSTRAINT "OT_OPERATION_U02" UNIQUE ("DESC_S")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."OT_OPERATION" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_OPERATION" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_OPERATION" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_OPERATION" MODIFY ("OPERATION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_OPERATION" MODIFY ("SIDE_APPLICABLE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_OPERATION" MODIFY ("SPECIALITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_OPERATION" MODIFY ("DESC_S" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_OPERATION" MODIFY ("DESC_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_OPERATION" MODIFY ("DESC_LONG" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_OPERATION" MODIFY ("CPT_CODE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_OPERATION" MODIFY ("ICD_CODE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_OPERATION" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_OPERATION" MODIFY ("ID" NOT NULL ENABLE);
