--------------------------------------------------------
--  Constraints for Table OT_RECOVERY_ROOM
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."OT_RECOVERY_ROOM" ADD CONSTRAINT "OT_RECOVERY_ROOM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."OT_RECOVERY_ROOM" ADD CONSTRAINT "OT_REC_ROOM_CODE_UK" UNIQUE ("ROOM_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."OT_RECOVERY_ROOM" ADD CONSTRAINT "OT_REC_ROOM_DESC_L_UK" UNIQUE ("LONG_DESC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."OT_RECOVERY_ROOM" ADD CONSTRAINT "OT_REC_ROOM_DESC_S_UK" UNIQUE ("DESC_S")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."OT_RECOVERY_ROOM" ADD CONSTRAINT "OT_REC_ROOM_DESC_P_UK" UNIQUE ("DESC_P")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."OT_RECOVERY_ROOM" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_RECOVERY_ROOM" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_RECOVERY_ROOM" MODIFY ("CHARGEABLE_ROOM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_RECOVERY_ROOM" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_RECOVERY_ROOM" MODIFY ("DESC_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_RECOVERY_ROOM" MODIFY ("DESC_S" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_RECOVERY_ROOM" MODIFY ("LONG_DESC" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_RECOVERY_ROOM" MODIFY ("ROOM_CODE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_RECOVERY_ROOM" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_RECOVERY_ROOM" MODIFY ("ID" NOT NULL ENABLE);
