--------------------------------------------------------
--  Constraints for Table OT_ROOM_STORE
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."OT_ROOM_STORE" ADD CONSTRAINT "OT_ROOM_STORE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."OT_ROOM_STORE" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_ROOM_STORE" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_ROOM_STORE" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_ROOM_STORE" MODIFY ("DEFAULT_STORE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_ROOM_STORE" MODIFY ("ROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_ROOM_STORE" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_ROOM_STORE" MODIFY ("ID" NOT NULL ENABLE);
