--------------------------------------------------------
--  Constraints for Table OT_TRANSACTIONS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."OT_TRANSACTIONS" ADD CONSTRAINT "OT_TRANSACTIONS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."OT_TRANSACTIONS" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_TRANSACTIONS" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_TRANSACTIONS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_TRANSACTIONS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_TRANSACTIONS" MODIFY ("OT_ORDER" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_TRANSACTIONS" MODIFY ("BOOKING_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_TRANSACTIONS" MODIFY ("CURRENT_LOCATION" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_TRANSACTIONS" MODIFY ("OPERATING_ROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_TRANSACTIONS" MODIFY ("CURRENT_STATUS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_TRANSACTIONS" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_TRANSACTIONS" MODIFY ("VISIT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_TRANSACTIONS" MODIFY ("ID" NOT NULL ENABLE);
