--------------------------------------------------------
--  Constraints for Table OT_USER_FUNCTIONS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."OT_USER_FUNCTIONS" ADD CONSTRAINT "OT_USER_FUNCTIONS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."OT_USER_FUNCTIONS" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_USER_FUNCTIONS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_USER_FUNCTIONS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_USER_FUNCTIONS" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_USER_FUNCTIONS" MODIFY ("FUNCTION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_USER_FUNCTIONS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."OT_USER_FUNCTIONS" MODIFY ("ID" NOT NULL ENABLE);
