--------------------------------------------------------
--  Constraints for Table PAS_OPS_GUARANTORS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PAS_OPS_GUARANTORS" ADD CONSTRAINT "PAS_OPS_GUARANTORS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_GUARANTORS" MODIFY ("ID" NOT NULL ENABLE);
