--------------------------------------------------------
--  Constraints for Table PAS_PATIENT_GUARANTORS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PAS_PATIENT_GUARANTORS" ADD CONSTRAINT "PAS_PATIENT_GUARANTORS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PAS_PATIENT_GUARANTORS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_PATIENT_GUARANTORS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_PATIENT_GUARANTORS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_PATIENT_GUARANTORS" MODIFY ("PRIORITY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_PATIENT_GUARANTORS" MODIFY ("INSURANCE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_PATIENT_GUARANTORS" MODIFY ("SUBSCRIBER_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_PATIENT_GUARANTORS" MODIFY ("CLASS_CODE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_PATIENT_GUARANTORS" MODIFY ("GUARANTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_PATIENT_GUARANTORS" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_PATIENT_GUARANTORS" MODIFY ("ID" NOT NULL ENABLE);
