--------------------------------------------------------
--  Constraints for Table PAS_OPS_SERVICES
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PAS_OPS_SERVICES" ADD CONSTRAINT "PAS_OPS_SERVICES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_SERVICES" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_SERVICES" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_SERVICES" MODIFY ("NEED_APPROVAL" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_SERVICES" MODIFY ("IS_EXCLUDED" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_SERVICES" MODIFY ("QTY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_SERVICES" MODIFY ("SERVICE_ITEM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_SERVICES" MODIFY ("PACKAGE_DISC" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_SERVICES" MODIFY ("CASH_DISC" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_SERVICES" MODIFY ("CONT_DISC" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_SERVICES" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_SERVICES" MODIFY ("PACKAGE_KEY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_SERVICES" MODIFY ("JOB_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_SERVICES" MODIFY ("SERIAL_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_SERVICES" MODIFY ("SECTION_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_SERVICES" MODIFY ("ELEMENT_CODE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_SERVICES" MODIFY ("GUARANTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_SERVICES" MODIFY ("SEQUENCE_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_SERVICES" MODIFY ("ID" NOT NULL ENABLE);
