--------------------------------------------------------
--  Constraints for Table PAS_ADT_STATEMENTS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PAS_ADT_STATEMENTS" ADD CONSTRAINT "PAS_ADT_STATEMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PAS_ADT_STATEMENTS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_ADT_STATEMENTS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_ADT_STATEMENTS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_ADT_STATEMENTS" MODIFY ("ENTRY_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_ADT_STATEMENTS" MODIFY ("PACKAGE_COVG_DISC" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_ADT_STATEMENTS" MODIFY ("TOTAL_PACKAGE_DISC" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_ADT_STATEMENTS" MODIFY ("TOTAL_CASH_DISC" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_ADT_STATEMENTS" MODIFY ("TOTAL_COVG_CONT_DISC" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_ADT_STATEMENTS" MODIFY ("TOTAL_COVG" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_ADT_STATEMENTS" MODIFY ("TOTAL" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_ADT_STATEMENTS" MODIFY ("DEPOSIT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_ADT_STATEMENTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_ADT_STATEMENTS" MODIFY ("ADMISSION_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_ADT_STATEMENTS" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_ADT_STATEMENTS" MODIFY ("ID" NOT NULL ENABLE);
