--------------------------------------------------------
--  Constraints for Table PAS_OPS_ELEMENTS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PAS_OPS_ELEMENTS" ADD CONSTRAINT "PAS_OPS_ELEMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_ELEMENTS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_ELEMENTS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_ELEMENTS" MODIFY ("TOTAL_PACKAGE_DISC" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_ELEMENTS" MODIFY ("CASH_DISC_EXCL" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_ELEMENTS" MODIFY ("TOTAL_CASH_DISC" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_ELEMENTS" MODIFY ("CONT_DISC_EXCL" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_ELEMENTS" MODIFY ("TOTAL_CONT_DISC" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_ELEMENTS" MODIFY ("TOTAL_EXCL" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_ELEMENTS" MODIFY ("TOTAL" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_ELEMENTS" MODIFY ("JOB_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_ELEMENTS" MODIFY ("SERIAL_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_ELEMENTS" MODIFY ("SECTION_NO" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_ELEMENTS" MODIFY ("ELEMENT_CODE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_ELEMENTS" MODIFY ("GUARANTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PAS_OPS_ELEMENTS" MODIFY ("ID" NOT NULL ENABLE);
