--------------------------------------------------------
--  Constraints for Table PHR_SIG_CODE
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PHR_SIG_CODE" ADD CONSTRAINT "PHR_SIG_CODE_PK" PRIMARY KEY ("SIG_CD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PHR_SIG_CODE" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_SIG_CODE" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_SIG_CODE" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_SIG_CODE" MODIFY ("UPDT_CNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_SIG_CODE" MODIFY ("SIG_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_SIG_CODE" MODIFY ("SIG_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_SIG_CODE" MODIFY ("LANGUAGE_CD" NOT NULL ENABLE);
