--------------------------------------------------------
--  Constraints for Table PHR_FILL_CYCLE
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PHR_FILL_CYCLE" ADD CONSTRAINT "PHR_FILL_CYCLE_PK" PRIMARY KEY ("FILL_CYCLE_ID", "LOCATION_CD", "DISPENSE_CATEGORY_CD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_CYCLE" MODIFY ("MODIFIED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_CYCLE" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_CYCLE" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_CYCLE" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_CYCLE" MODIFY ("TO_TZ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_CYCLE" MODIFY ("FROM_TZ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_CYCLE" MODIFY ("UPDT_CNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_CYCLE" MODIFY ("LAST_OPERATION_FLAG" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_CYCLE" MODIFY ("TO_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_CYCLE" MODIFY ("FROM_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_CYCLE" MODIFY ("DISPENSE_CATEGORY_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_CYCLE" MODIFY ("LOCATION_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_CYCLE" MODIFY ("FILL_CYCLE_ID" NOT NULL ENABLE);
