--------------------------------------------------------
--  Constraints for Table PHR_ORDER_COMMENTS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_COMMENTS" ADD CONSTRAINT "PHR_ORDER_COMMENTS_PK" PRIMARY KEY ("CPMMENT_PRSNL_ID", "COMMENT_TYPE_CD", "ORDER_ID", "LONG_TEXT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_COMMENTS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_COMMENTS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_COMMENTS" MODIFY ("LONG_TEXT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_COMMENTS" MODIFY ("UPDT_CNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_COMMENTS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_COMMENTS" MODIFY ("COMMENT_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_COMMENTS" MODIFY ("CPMMENT_PRSNL_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_COMMENTS" MODIFY ("COMMENT_DT_TM" NOT NULL ENABLE);
