--------------------------------------------------------
--  Constraints for Table PHR_WORKFLOW_TYPES
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PHR_WORKFLOW_TYPES" ADD CONSTRAINT "PHR_WORKFLOW_TYPES_PK" PRIMARY KEY ("WORKFLOW_ITEM_ID", "WORKFLOW_EVENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PHR_WORKFLOW_TYPES" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_WORKFLOW_TYPES" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_WORKFLOW_TYPES" MODIFY ("UPDT_CNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_WORKFLOW_TYPES" MODIFY ("WORKFLOW_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_WORKFLOW_TYPES" MODIFY ("ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_WORKFLOW_TYPES" MODIFY ("WORKFLOW_EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_WORKFLOW_TYPES" MODIFY ("WORKFLOW_ITEM_ID" NOT NULL ENABLE);
