--------------------------------------------------------
--  Constraints for Table PHR_MED_PACKAGE_TYPES
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PHR_MED_PACKAGE_TYPES" ADD CONSTRAINT "PHR_MED_PACKAGE_TYPES_PK" PRIMARY KEY ("MED_PACKAGE_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PHR_MED_PACKAGE_TYPES" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MED_PACKAGE_TYPES" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MED_PACKAGE_TYPES" MODIFY ("ACTIVE_IND" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MED_PACKAGE_TYPES" MODIFY ("UPDT_CNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MED_PACKAGE_TYPES" MODIFY ("UOM_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MED_PACKAGE_TYPES" MODIFY ("MED_PACKAGE_TYPE_ID" NOT NULL ENABLE);
