--------------------------------------------------------
--  Constraints for Table PHR_MEDICATION_INVENTORY
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION_INVENTORY" ADD CONSTRAINT "PHR_MEDICATION_INVENTORY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION_INVENTORY" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION_INVENTORY" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION_INVENTORY" MODIFY ("UPDATE_COUNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION_INVENTORY" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION_INVENTORY" MODIFY ("MEDICATION_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION_INVENTORY" MODIFY ("LOCATION_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION_INVENTORY" MODIFY ("LOCATION_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION_INVENTORY" MODIFY ("ID" NOT NULL ENABLE);
