--------------------------------------------------------
--  Constraints for Table PHR_STANDARDIZED_DOSE_RANGE
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PHR_STANDARDIZED_DOSE_RANGE" ADD CONSTRAINT "PHR_STANDARDIZED_DOSE_RANG_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PHR_STANDARDIZED_DOSE_RANGE" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_STANDARDIZED_DOSE_RANGE" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_STANDARDIZED_DOSE_RANGE" MODIFY ("UPDATE_COUNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_STANDARDIZED_DOSE_RANGE" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_STANDARDIZED_DOSE_RANGE" MODIFY ("MEDICATION_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_STANDARDIZED_DOSE_RANGE" MODIFY ("STD_DOSE_UNIT_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_STANDARDIZED_DOSE_RANGE" MODIFY ("STD_DOSE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_STANDARDIZED_DOSE_RANGE" MODIFY ("ROUTE_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_STANDARDIZED_DOSE_RANGE" MODIFY ("RELATIONAL_OPERATOR" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_STANDARDIZED_DOSE_RANGE" MODIFY ("COMPARE_UNIT_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_STANDARDIZED_DOSE_RANGE" MODIFY ("SECOND_VALUE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_STANDARDIZED_DOSE_RANGE" MODIFY ("FIRST_VALUE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_STANDARDIZED_DOSE_RANGE" MODIFY ("ID" NOT NULL ENABLE);
