--------------------------------------------------------
--  Constraints for Table PHR_DISPENSE_CAT
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_CAT" ADD CONSTRAINT "PHR_DISPENSE_CAT_PK" PRIMARY KEY ("DISPENSE_CATEGORY_CD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_CAT" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_CAT" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_CAT" MODIFY ("ACTIVE_IND" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_CAT" MODIFY ("UPDT_TASK" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_CAT" MODIFY ("UPDT_CNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_CAT" MODIFY ("LABEL_FORMAT_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_CAT" MODIFY ("ORDER_TYPE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_CAT" MODIFY ("PRICE_SCHED_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_CAT" MODIFY ("DISPENSE_CATEGORY_CD" NOT NULL ENABLE);
