--------------------------------------------------------
--  Constraints for Table PHR_UNITS_MEASURE
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PHR_UNITS_MEASURE" ADD CONSTRAINT "PHR_UNITS_MEASURE_PK" PRIMARY KEY ("UNITS_OF_MEASURE_CD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PHR_UNITS_MEASURE" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_UNITS_MEASURE" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_UNITS_MEASURE" MODIFY ("ACTIVE_IND" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_UNITS_MEASURE" MODIFY ("UPDT_CNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_UNITS_MEASURE" MODIFY ("UNITS_OF_MEASURE_CD" NOT NULL ENABLE);
