--------------------------------------------------------
--  Constraints for Table PHR_ORDER_CATALOG_SYNONYM
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_CATALOG_SYNONYM" ADD CONSTRAINT "PHR_ORDER_CATALOG_SYNONYM_PK" PRIMARY KEY ("SYNONYM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_CATALOG_SYNONYM" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_CATALOG_SYNONYM" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_CATALOG_SYNONYM" MODIFY ("UPDT_CNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_CATALOG_SYNONYM" MODIFY ("SYNONYM_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_CATALOG_SYNONYM" MODIFY ("ORDER_SENTENCE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_CATALOG_SYNONYM" MODIFY ("ORDERABLE_TYPE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_CATALOG_SYNONYM" MODIFY ("OE_FORMAT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_CATALOG_SYNONYM" MODIFY ("MULTIPLE_ORD_SENT_IND" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_CATALOG_SYNONYM" MODIFY ("MNEMONIC_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_CATALOG_SYNONYM" MODIFY ("ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_CATALOG_SYNONYM" MODIFY ("HIGH_ALERT_LONG_TEXT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_CATALOG_SYNONYM" MODIFY ("HIGH_ALERT_IND" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_CATALOG_SYNONYM" MODIFY ("HIDE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_CATALOG_SYNONYM" MODIFY ("DCP_CLIN_CAT_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_CATALOG_SYNONYM" MODIFY ("CATALOG_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_CATALOG_SYNONYM" MODIFY ("CATALOG_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_CATALOG_SYNONYM" MODIFY ("ACTIVITY_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_CATALOG_SYNONYM" MODIFY ("MULTUM_DRUG_IDENTIFIER" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_CATALOG_SYNONYM" MODIFY ("ACTIVE_IND" NOT NULL ENABLE);
