--------------------------------------------------------
--  Constraints for Table PHR_ITEM_INV_LOC
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PHR_ITEM_INV_LOC" ADD CONSTRAINT "PHR_ITEM_INV_LOC_PK" PRIMARY KEY ("LOCATION_CD", "ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PHR_ITEM_INV_LOC" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ITEM_INV_LOC" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ITEM_INV_LOC" MODIFY ("UPDT_CNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ITEM_INV_LOC" MODIFY ("PACKAGE_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ITEM_INV_LOC" MODIFY ("LOCATION_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ITEM_INV_LOC" MODIFY ("ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ITEM_INV_LOC" MODIFY ("EXP_DATE_TM" NOT NULL ENABLE);
