--------------------------------------------------------
--  Constraints for Table PHR_MED_MANIFACTURING_DETAILS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PHR_MED_MANIFACTURING_DETAILS" ADD CONSTRAINT "PHR_MED_MANIFACTURING_DETA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PHR_MED_MANIFACTURING_DETAILS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MED_MANIFACTURING_DETAILS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MED_MANIFACTURING_DETAILS" MODIFY ("UPDATE_COUNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MED_MANIFACTURING_DETAILS" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MED_MANIFACTURING_DETAILS" MODIFY ("MEDICATION_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MED_MANIFACTURING_DETAILS" MODIFY ("FORMULARY_STATUS_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MED_MANIFACTURING_DETAILS" MODIFY ("PRIMARY_MANF_ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MED_MANIFACTURING_DETAILS" MODIFY ("OUTER_PACKAGE_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MED_MANIFACTURING_DETAILS" MODIFY ("INNER_PACKAGE_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MED_MANIFACTURING_DETAILS" MODIFY ("MANUFACTURER_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MED_MANIFACTURING_DETAILS" MODIFY ("UNIT_DOSE_IND" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MED_MANIFACTURING_DETAILS" MODIFY ("BRAND_IND" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MED_MANIFACTURING_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
