--------------------------------------------------------
--  Constraints for Table PHR_ORDER_DISPENSE
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" ADD CONSTRAINT "PHR_ORDER_DISPENSE_PK" PRIMARY KEY ("ORDER_ID", "PATIENT_ID", "NEED_RX_VERIFY_IND", "UNVERIFIED_COMM_TYPE_CD", "UNVERIFIED_ROUTE_CD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("PATIENT_MED_IND" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("START_DISPENSE_TZ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("START_DISPENSE_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("WORKFLOW_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("SUSPEND_DT_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("STOP_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("RESUME_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("PROFILE_DISPLAY_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("NEXT_DISPENSE_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("LAST_REFILL_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("EXPIRE_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("CART_FILL_DATE_TM3" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("CART_FILL_DATE_TM2" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("CART_FILL_DATE_TM1" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("UNVERIFIED_ROUTE_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("UNVERIFIED_COMM_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("NEED_RX_VERIFY_IND" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("LAST_REFILL_TZ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("SUSPEND_TZ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("STOP_TZ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("CART_FILL3_TZ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("CART_FILL2_TZ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("CART_FILL1_TZ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("NEXT_DISPENSE_TZ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("LAST_FILL_ACT_SEQ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("PHARM_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("LEGAL_STATUS_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("LAST_FILL_HX_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("LAST_FILL_DISPENSE_HX_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("DAW_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("RX_NBR_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("PRICE_CODE_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("STOP_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("REPLACE_EVERY_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("PRICE_SCHEDULE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("ORDER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("ORDER_PRICE_VALUE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("ORDER_DISPENSE_IND" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("ORDER_COST_VALUE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("LAST_VER_ACT_SEQ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("FREQUENCY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("CART_FILL_DOSES3" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("CART_FILL_DOSES2" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("CART_FILL_DOSES1" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("FLOORSTOCK_IND" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("UPDT_CNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("TOTAL_DISPENSE_DOSE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("PRN_IND" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("EPISODE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("DISPENSE_CATEGORY_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ORDER_DISPENSE" MODIFY ("ORDER_ID" NOT NULL ENABLE);
