--------------------------------------------------------
--  Constraints for Table PHR_FREQUENCY_SCHEDULE
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PHR_FREQUENCY_SCHEDULE" ADD CONSTRAINT "PHR_FREQUENCY_SCHEDULE_PK" PRIMARY KEY ("FREQUENCY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PHR_FREQUENCY_SCHEDULE" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FREQUENCY_SCHEDULE" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FREQUENCY_SCHEDULE" MODIFY ("EFFECTIVE_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FREQUENCY_SCHEDULE" MODIFY ("FACILITY_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FREQUENCY_SCHEDULE" MODIFY ("PRN_DEFAULT_IND" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FREQUENCY_SCHEDULE" MODIFY ("UPDT_CNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FREQUENCY_SCHEDULE" MODIFY ("ACTIVE_IND" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FREQUENCY_SCHEDULE" MODIFY ("FREQUENCY_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FREQUENCY_SCHEDULE" MODIFY ("FREQUENCY_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FREQUENCY_SCHEDULE" MODIFY ("FREQUENCY_ID" NOT NULL ENABLE);
