--------------------------------------------------------
--  Constraints for Table PHR_QUANTITY_ON_HAND
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PHR_QUANTITY_ON_HAND" ADD CONSTRAINT "PHR_QUANTITY_ON_HAND_PK" PRIMARY KEY ("ITEM_ID", "LOCATION_CD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PHR_QUANTITY_ON_HAND" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_QUANTITY_ON_HAND" MODIFY ("CRAETED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_QUANTITY_ON_HAND" MODIFY ("UPDT_CNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_QUANTITY_ON_HAND" MODIFY ("QTY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_QUANTITY_ON_HAND" MODIFY ("PACKAGE_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_QUANTITY_ON_HAND" MODIFY ("LOCATION_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_QUANTITY_ON_HAND" MODIFY ("ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_QUANTITY_ON_HAND" MODIFY ("ACTIVE_STATUS_DT_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_QUANTITY_ON_HAND" MODIFY ("ACTIVE_STATUS_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_QUANTITY_ON_HAND" MODIFY ("ACTIVE_IND" NOT NULL ENABLE);
