--------------------------------------------------------
--  Constraints for Table PHR_ROUTE_FORM
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PHR_ROUTE_FORM" ADD CONSTRAINT "PHR_ROUTE_FORM_PK" PRIMARY KEY ("FORM_CD", "ROUTE_CD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PHR_ROUTE_FORM" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ROUTE_FORM" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ROUTE_FORM" MODIFY ("ACTIVE_IND" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_ROUTE_FORM" MODIFY ("UPDT_CNT" NOT NULL ENABLE);
