--------------------------------------------------------
--  Constraints for Table PHR_WORKFLOW_ACTION_LOGS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PHR_WORKFLOW_ACTION_LOGS" ADD CONSTRAINT "PHR_WORKFLOW_ACTION_LOGS_PK" PRIMARY KEY ("WORKFLOW_EVENT_HX_ID", "WORKFLOW_EVENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PHR_WORKFLOW_ACTION_LOGS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_WORKFLOW_ACTION_LOGS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_WORKFLOW_ACTION_LOGS" MODIFY ("UPDT_TZ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_WORKFLOW_ACTION_LOGS" MODIFY ("UPDT_CNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_WORKFLOW_ACTION_LOGS" MODIFY ("WORKFLOW_STS_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_WORKFLOW_ACTION_LOGS" MODIFY ("WORKFLOW_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_WORKFLOW_ACTION_LOGS" MODIFY ("WORKFLOW_EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_WORKFLOW_ACTION_LOGS" MODIFY ("WORKFLOW_EVENT_HX_ID" NOT NULL ENABLE);
