--------------------------------------------------------
--  Constraints for Table PHR_MEDICATION
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION" ADD CONSTRAINT "PHR_MEDICATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION" MODIFY ("UPDATE_COUNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION" MODIFY ("ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION" MODIFY ("INGREDIENT_IND" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION" MODIFY ("PHARMACY_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION" MODIFY ("MED_PACKAGE_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION" MODIFY ("MED_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION" MODIFY ("NDC_S" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION" MODIFY ("NDC_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION" MODIFY ("MNEMONIC_S" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION" MODIFY ("MNEMONIC_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION" MODIFY ("GENERIC_NAME_S" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION" MODIFY ("GENERIC_NAME_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION" MODIFY ("DESC_S" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION" MODIFY ("DESC_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION" MODIFY ("BRAND_NAME_S" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION" MODIFY ("BRAND_NAME_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_MEDICATION" MODIFY ("ID" NOT NULL ENABLE);
