--------------------------------------------------------
--  Constraints for Table PHR_FILL_PRINT_LOG
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PHR_FILL_PRINT_LOG" ADD CONSTRAINT "PHR_FILL_PRINT_LOG_PK" PRIMARY KEY ("RUN_ID", "RUN_TYPE_CD", "FILL_BATCH_CD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_PRINT_LOG" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_PRINT_LOG" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_PRINT_LOG" MODIFY ("CYC_TO_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_PRINT_LOG" MODIFY ("CYC_FROM_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_PRINT_LOG" MODIFY ("CYC_TO_TZ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_PRINT_LOG" MODIFY ("CYC_FROM_TZ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_PRINT_LOG" MODIFY ("BATCH_REPORT_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_PRINT_LOG" MODIFY ("OUTPUT_DEVICE_S" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_PRINT_LOG" MODIFY ("OUTPUT_DEVICE_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_PRINT_LOG" MODIFY ("OUTPUT_FORMAT_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_PRINT_LOG" MODIFY ("FILL_BATCH_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_PRINT_LOG" MODIFY ("FILL_HX_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_PRINT_LOG" MODIFY ("RUN_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_PRINT_LOG" MODIFY ("RUN_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_PRINT_LOG" MODIFY ("RUN_ID" NOT NULL ENABLE);
