--------------------------------------------------------
--  Constraints for Table PHR_DISPENSE_LOGS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" ADD CONSTRAINT "PHR_DISPENSE_LOGS_PK" PRIMARY KEY ("DISPENSE_HX_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" MODIFY ("FUTURE_CHARGE_IND" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" MODIFY ("FIRST_DOSE_TIME" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" MODIFY ("CHARGE_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" MODIFY ("DISP_PRIORITY_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" MODIFY ("DISPENSE_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" MODIFY ("PREV_DISPENSE_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" MODIFY ("NEXT_DISPENSE_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" MODIFY ("FIRST_DOSE_TZ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" MODIFY ("DISP_PRIORITY_TZ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" MODIFY ("DISPENSE_TZ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" MODIFY ("PREV_DISPENSE_TZ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" MODIFY ("NEXT_DISPENSE_TZ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" MODIFY ("DISP_LOC_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" MODIFY ("DISP_QTY_UNIT_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" MODIFY ("PHARM_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" MODIFY ("DISP_PRIORITY_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" MODIFY ("UPDT_CNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" MODIFY ("RUN_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" MODIFY ("FILL_HX_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" MODIFY ("REASON_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" MODIFY ("DISP_EVENT_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" MODIFY ("ACTION_SEQUENCE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" MODIFY ("DISPENSE_HX_ID" NOT NULL ENABLE);
