--------------------------------------------------------
--  Constraints for Table PHR_PACKAGE_TYPE
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PHR_PACKAGE_TYPE" ADD CONSTRAINT "PHR_PACKAGE_TYPE_PK" PRIMARY KEY ("ITEM_ID", "PACKAGE_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PHR_PACKAGE_TYPE" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_PACKAGE_TYPE" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_PACKAGE_TYPE" MODIFY ("UPDT_CNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_PACKAGE_TYPE" MODIFY ("PACKAGE_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_PACKAGE_TYPE" MODIFY ("ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_PACKAGE_TYPE" MODIFY ("ACTIVE_IND" NOT NULL ENABLE);
