--------------------------------------------------------
--  Constraints for Table PHR_FILL_CYCLE_BATCH
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PHR_FILL_CYCLE_BATCH" ADD CONSTRAINT "PHR_FILL_CYCLE_BATCH_PK" PRIMARY KEY ("LOCATION_CD", "FILL_BATCH_CD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_CYCLE_BATCH" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_CYCLE_BATCH" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_CYCLE_BATCH" MODIFY ("UPDT_CNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_CYCLE_BATCH" MODIFY ("DISPENSE_CATEGORY_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_CYCLE_BATCH" MODIFY ("LOCATION_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_CYCLE_BATCH" MODIFY ("FILL_BATCH_CD" NOT NULL ENABLE);
