--------------------------------------------------------
--  Constraints for Table PHR_FILL_BATCH
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH" ADD CONSTRAINT "PHR_FILL_BATCH_PK" PRIMARY KEY ("FILL_BATCH_CD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH" MODIFY ("LOC_FACILITY_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH" MODIFY ("LOCATION_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH" MODIFY ("ORDER_TYPE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH" MODIFY ("DEFAULT_PRINTER_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH" MODIFY ("OUTPUT_FORMAT_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH" MODIFY ("MAX_CYCLE_UNIT_FLAG" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH" MODIFY ("MAX_CYCLE_TIME" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH" MODIFY ("DISCONTINUE_UNIT_FLAG" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH" MODIFY ("DISCONTINUE_TIME" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH" MODIFY ("CYCLE_UNIT_FLAG" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH" MODIFY ("CYCLE_TIME" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH" MODIFY ("FILL_BATCH_CD" NOT NULL ENABLE);
