--------------------------------------------------------
--  Constraints for Table PHR_REASON_EVENT
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PHR_REASON_EVENT" ADD CONSTRAINT "PHR_REASON_EVENT_PK" PRIMARY KEY ("REASON_CD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PHR_REASON_EVENT" MODIFY ("CREADET_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_REASON_EVENT" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_REASON_EVENT" MODIFY ("ACTIVE_IND" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_REASON_EVENT" MODIFY ("UPDT_CNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_REASON_EVENT" MODIFY ("EVENT_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_REASON_EVENT" MODIFY ("REASON_CD" NOT NULL ENABLE);
