--------------------------------------------------------
--  Constraints for Table PHR_FILL_BATCH_LOG
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" ADD CONSTRAINT "PHR_FILL_BATCH_LOG_PK" PRIMARY KEY ("FILL_HX_ID", "FILL_AUDIT_FLAG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("START_TZ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("TO_TZ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("FROM_TZ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("LOCATION_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("TO_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("FROM_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("ORDER_COUNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("PRINT_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("DIS_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("FILL_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("END_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("START_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("UPDT_CNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("RUN_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("OUTPUT_DEVICE_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("OUTPUT_FORMAT_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("MAX_CYCLE_UNIT_FLAG" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("MAX_CYCLE_TIME" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("MAX_FILL_UNIT_FLAG" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("MAX_FILL_TIME" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("SUSPEND_TIME" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("FILL_UNIT_FLAG" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("FILL_TIME" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("FILL_BATCH_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("FILL_AUDIT_FLAG" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" MODIFY ("FILL_HX_ID" NOT NULL ENABLE);
