--------------------------------------------------------
--  Constraints for Table PRC_LIST
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."PRC_LIST" ADD CONSTRAINT "PRC_LIST_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."PRC_LIST" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PRC_LIST" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PRC_LIST" MODIFY ("IS_STANDARD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PRC_LIST" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PRC_LIST" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."PRC_LIST" MODIFY ("ID" NOT NULL ENABLE);
