--------------------------------------------------------
--  Constraints for Table SAP_APPOINTMENTS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."SAP_APPOINTMENTS" ADD CONSTRAINT "SAP_APPOINTMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."SAP_APPOINTMENTS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."SAP_APPOINTMENTS" MODIFY ("APPT_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."SAP_APPOINTMENTS" MODIFY ("CAT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."SAP_APPOINTMENTS" MODIFY ("IS_WAITING" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."SAP_APPOINTMENTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."SAP_APPOINTMENTS" MODIFY ("ENTRY_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."SAP_APPOINTMENTS" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."SAP_APPOINTMENTS" MODIFY ("RESOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."SAP_APPOINTMENTS" MODIFY ("ID" NOT NULL ENABLE);
