--------------------------------------------------------
--  Constraints for Table SS2K5_INDEX_COLUMNS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."SS2K5_INDEX_COLUMNS" MODIFY ("COLUMN_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."SS2K5_INDEX_COLUMNS" MODIFY ("INDEX_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."SS2K5_INDEX_COLUMNS" MODIFY ("OBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."SS2K5_INDEX_COLUMNS" MODIFY ("INDEX_COLUMN_ID" NOT NULL ENABLE);
