--------------------------------------------------------
--  Constraints for Table SS2K5_COLUMNS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."SS2K5_COLUMNS" MODIFY ("OBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."SS2K5_COLUMNS" MODIFY ("DEFAULT_OBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."SS2K5_COLUMNS" MODIFY ("SYSTEM_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."SS2K5_COLUMNS" MODIFY ("USER_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."SS2K5_COLUMNS" MODIFY ("SCALE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."SS2K5_COLUMNS" MODIFY ("PRECISION" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."SS2K5_COLUMNS" MODIFY ("MAX_LENGTH" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."SS2K5_COLUMNS" MODIFY ("COLUMN_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."SS2K5_COLUMNS" MODIFY ("RULE_OBJECT_ID" NOT NULL ENABLE);
