--------------------------------------------------------
--  Constraints for Table SS2K5_DATABASE_PRINCIPALS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."SS2K5_DATABASE_PRINCIPALS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."SS2K5_DATABASE_PRINCIPALS" MODIFY ("PRINCIPAL_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."SS2K5_DATABASE_PRINCIPALS" MODIFY ("TYPE" NOT NULL ENABLE);
