--------------------------------------------------------
--  Constraints for Table STAGE_SS2K5_DB_PRINCIPALS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."STAGE_SS2K5_DB_PRINCIPALS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."STAGE_SS2K5_DB_PRINCIPALS" MODIFY ("PRINCIPAL_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."STAGE_SS2K5_DB_PRINCIPALS" MODIFY ("TYPE" NOT NULL ENABLE);
