--------------------------------------------------------
--  Constraints for Table STAGE_SS2K5_FN_KEY_COLUMNS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."STAGE_SS2K5_FN_KEY_COLUMNS" MODIFY ("REFERENCED_OBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."STAGE_SS2K5_FN_KEY_COLUMNS" MODIFY ("REFERENCED_COLUMN_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."STAGE_SS2K5_FN_KEY_COLUMNS" MODIFY ("PARENT_COLUMN_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."STAGE_SS2K5_FN_KEY_COLUMNS" MODIFY ("PARENT_OBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."STAGE_SS2K5_FN_KEY_COLUMNS" MODIFY ("CONSTRAINT_OBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."STAGE_SS2K5_FN_KEY_COLUMNS" MODIFY ("CONSTRAINT_COLUMN_ID" NOT NULL ENABLE);
