--------------------------------------------------------
--  Constraints for Table STAGE_SS2K5_TABLES
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."STAGE_SS2K5_TABLES" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."STAGE_SS2K5_TABLES" MODIFY ("SCHEMA_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."STAGE_SS2K5_TABLES" MODIFY ("OBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."STAGE_SS2K5_TABLES" MODIFY ("NAME" NOT NULL ENABLE);
