--------------------------------------------------------
--  Constraints for Table STAGE_SS2K5_SYSPROPERTIES
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."STAGE_SS2K5_SYSPROPERTIES" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."STAGE_SS2K5_SYSPROPERTIES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."STAGE_SS2K5_SYSPROPERTIES" MODIFY ("MINOR_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."STAGE_SS2K5_SYSPROPERTIES" MODIFY ("MAJOR_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."STAGE_SS2K5_SYSPROPERTIES" MODIFY ("CLASS" NOT NULL ENABLE);
