--------------------------------------------------------
--  DDL for Table ADT_PATIENTS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."ADT_PATIENTS" 
   (	"ID" RAW(32), 
	"FACILITY_ID" NUMBER, 
	"PATIENT_CODE" VARCHAR2(50 CHAR), 
	"ADMISSION_ID" NUMBER, 
	"IS_RESIDENT" NUMBER(1,0), 
	"FIRST_NAME_P" VARCHAR2(30 CHAR), 
	"FATHER_NAME_P" VARCHAR2(30 CHAR), 
	"MID_NAME_P" VARCHAR2(30 CHAR), 
	"LAST_NAME_P" VARCHAR2(30 CHAR), 
	"FIRST_NAME_S" VARCHAR2(30 CHAR), 
	"FATHER_NAME_S" VARCHAR2(30 CHAR), 
	"MID_NAME_S" VARCHAR2(30 CHAR), 
	"LAST_NAME_S" VARCHAR2(30 CHAR), 
	"BIRTH_DATE" DATE, 
	"GENDER" NUMBER(1,0), 
	"MARITAL_STATUS" NUMBER(1,0), 
	"RELIGION_ID" NUMBER, 
	"NATIONALITY_ID" NUMBER, 
	"NATIONAL_CODE" VARCHAR2(50 CHAR), 
	"BLOOD_GROUP_ID" NUMBER(2,0), 
	"COUNTRY_ID" NUMBER, 
	"CITY_ID" NUMBER, 
	"ZIP_CODE" VARCHAR2(30 CHAR), 
	"POBOX" VARCHAR2(30 CHAR), 
	"ADDRESS" VARCHAR2(100 CHAR), 
	"E_MAIL" VARCHAR2(50 CHAR), 
	"SPOUSE_NAME_P" VARCHAR2(30 CHAR), 
	"SPOUSE_NAME_S" VARCHAR2(30 CHAR), 
	"ENTRY_DATE" DATE, 
	"HEIGHT" NUMBER(3,0), 
	"WEIGHT" NUMBER(3,0), 
	"BODY_MASS" NUMBER(3,0), 
	"IS_DIED" NUMBER(1,0), 
	"MOTHER_NAME" VARCHAR2(150 CHAR), 
	"PATIENT_TYPE_ID" NUMBER, 
	"REMARKS" VARCHAR2(1000 CHAR), 
	"PATIENT_IMAGE" VARCHAR2(2000 CHAR), 
	"OPINING_SECTION" NUMBER(6,0), 
	"NEW_PATIENT_CODE" VARCHAR2(30 CHAR), 
	"FILE_LOCATION" NUMBER(6,0), 
	"FILE_CREATION_DATE" DATE, 
	"STATUS" NUMBER(1,0), 
	"EMPLOYEE_ID" NUMBER, 
	"UNKNOWN_SERIAL_NO" VARCHAR2(30 CHAR), 
	"IS_UNKNOWN" NUMBER(1,0), 
	"TEL_TYPE" NUMBER(1,0), 
	"TEL_CODE" VARCHAR2(50 CHAR), 
	"FAMILY_FILE_CODE" VARCHAR2(30 CHAR), 
	"IS_HEAD_OF_FAMILY" NUMBER(1,0), 
	"IS_ARCHIVED" NUMBER(1,0), 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"AGE" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
