--------------------------------------------------------
--  DDL for Table ADT_TRANSFERS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."ADT_TRANSFERS" 
   (	"ID" NUMBER, 
	"FACILITY_ID" NUMBER, 
	"PATIENT_ID" RAW(32), 
	"ADMISSION_ID" NUMBER, 
	"HAS_COMPANION" NUMBER(1,0), 
	"SECTION_ID" NUMBER, 
	"ROOM_ID" NUMBER, 
	"BED_ID" NUMBER, 
	"IS_ADDITIONAL_BED" NUMBER(1,0), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"REQUESTED_CLASS_ID" NUMBER, 
	"ACTUAL_CLASS_ID" NUMBER, 
	"ENTRY_DATE" DATE, 
	"REMARKS" VARCHAR2(250 BYTE), 
	"TRANSFER_REASON_ID" NUMBER, 
	"APPROVAL_REMARKS" VARCHAR2(250 BYTE), 
	"APPROVED_BY" NUMBER, 
	"APPROVAL_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
