--------------------------------------------------------
--  DDL for Table ADT_BEDS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."ADT_BEDS" 
   (	"ID" NUMBER, 
	"FACILITY_ID" NUMBER, 
	"SECTION_ID" NUMBER, 
	"ROOM_ID" NUMBER, 
	"CODE" VARCHAR2(20 BYTE), 
	"TELEPHONE_CODE" VARCHAR2(20 BYTE), 
	"STATUS" NUMBER(1,0), 
	"PATIENT_ID" RAW(32), 
	"ADMISSION_ID" NUMBER, 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
