--------------------------------------------------------
--  DDL for Table ADT_ROOMS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."ADT_ROOMS" 
   (	"ID" NUMBER, 
	"FACILITY_ID" NUMBER, 
	"SECTION_ID" NUMBER, 
	"CODE" VARCHAR2(20 BYTE), 
	"BED_COUNT" NUMBER(3,0), 
	"GENDER" NUMBER(1,0), 
	"IS_ISOLATED" NUMBER(1,0), 
	"STATUS" NUMBER(1,0), 
	"LOCATION" VARCHAR2(1000 BYTE), 
	"CLASS_ID" NUMBER, 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
