--------------------------------------------------------
--  DDL for Table ADT_ADMISSION_REASONS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."ADT_ADMISSION_REASONS" 
   (	"ID" NUMBER, 
	"FACILITY_ID" NUMBER, 
	"CODE" VARCHAR2(20 BYTE), 
	"DESC_P" VARCHAR2(500 BYTE), 
	"DESC_S" VARCHAR2(500 BYTE), 
	"CREATED_BY" NUMBER, 
	"MODIFIED_BY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
