--------------------------------------------------------
--  DDL for Table ADT_PATIENT_DOCUMENTS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."ADT_PATIENT_DOCUMENTS" 
   (	"ID" NUMBER, 
	"PATIENT_ID" RAW(32), 
	"DOCUMENT_CODE" VARCHAR2(20 BYTE), 
	"DOCUMENT_ID" NUMBER, 
	"ISSUE_DATE" DATE, 
	"EXPIRY_DATE" DATE, 
	"URL" VARCHAR2(1000 BYTE), 
	"COUNTRY_ID" NUMBER, 
	"NOTES" VARCHAR2(2000 BYTE), 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
