--------------------------------------------------------
--  DDL for Table ADT_DIAGNOSIS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."ADT_DIAGNOSIS" 
   (	"ID" NUMBER, 
	"FACILITY_ID" NUMBER, 
	"PATIENT_ID" RAW(32), 
	"ADMISSION_ID" NUMBER, 
	"DIAGNOSIS_TYPE" NUMBER(1,0), 
	"DIAGNOSIS_ID" NUMBER, 
	"IS_CHRONICAL" NUMBER(1,0), 
	"IS_PREEXISTING" NUMBER(1,0), 
	"APPEARANCE_DATE" DATE, 
	"IS_ADMISSION_REASON" NUMBER(1,0), 
	"IS_POMR_ACTIVATED" NUMBER(1,0), 
	"IS_POST_OPERATIVE" NUMBER(1,0), 
	"IS_ADMISSION_DIAG" NUMBER(1,0), 
	"IS_DISVARCHARGE_DIAG" NUMBER(1,0), 
	"ENTRY_DATE" DATE, 
	"DOCTOR_ID" NUMBER, 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
