--------------------------------------------------------
--  DDL for Table ADT_COMPANIONS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."ADT_COMPANIONS" 
   (	"ID" NUMBER, 
	"FACILITY_ID" NUMBER, 
	"PATIENT_ID" RAW(32), 
	"ADMISSION_ID" NUMBER, 
	"FIRST_NAME_P" VARCHAR2(30 BYTE), 
	"FATHER_NAME_P" VARCHAR2(30 BYTE), 
	"MID_NAME_P" VARCHAR2(30 BYTE), 
	"LAST_NAME_P" VARCHAR2(30 BYTE), 
	"FIRST_NAME_S" VARCHAR2(30 BYTE), 
	"FATHER_NAME_S" VARCHAR2(30 BYTE), 
	"MID_NAME_S" VARCHAR2(30 BYTE), 
	"LAST_NAME_S" VARCHAR2(30 BYTE), 
	"AGE" NUMBER(3,0), 
	"GENDER" NUMBER(1,0), 
	"DOC_CODE" VARCHAR2(20 BYTE), 
	"REGISTRATION_DATE" DATE, 
	"DISCHARGE_DATE" DATE, 
	"SECTION_ID" NUMBER, 
	"ROOM_ID" NUMBER, 
	"BED_ID" NUMBER, 
	"PC_NAME" VARCHAR2(100 BYTE), 
	"ENTRY_DATE" DATE, 
	"ACTUAL_CLASS_ID" NUMBER, 
	"REQUESTED_CLASS_ID" NUMBER, 
	"NOTIFY_ID" NUMBER, 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"TEL_CODE" VARCHAR2(20 BYTE), 
	"NATIONALITY_ID" NUMBER, 
	"RELATIONSHIP_ID" NUMBER, 
	"IS_MEAL_PROVIDED" NUMBER(1,0), 
	"DOC_ID" NUMBER, 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"TEL_TYPE" NUMBER(1,0), 
	"NATIONAL_CODE" VARCHAR2(50 BYTE), 
	"IS_ADDITIONAL_BED" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
