--------------------------------------------------------
--  DDL for Table ADT_PATIENT_KINS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."ADT_PATIENT_KINS" 
   (	"ID" NUMBER, 
	"FACILITY_ID" NUMBER, 
	"PATIENT_ID" RAW(32), 
	"NAME_P" VARCHAR2(100 BYTE), 
	"NAME_S" VARCHAR2(100 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(300 BYTE), 
	"DOC_ID" NUMBER, 
	"DOC_CODE" VARCHAR2(20 BYTE), 
	"RELATIONSHIP_ID" NUMBER, 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"BIRTH_DATE" DATE, 
	"GENDER" NUMBER(1,0), 
	"NATIONALITY_ID" NUMBER, 
	"NATIONAL_CODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
