--------------------------------------------------------
--  DDL for Table ADT_CLASSES
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."ADT_CLASSES" 
   (	"ID" NUMBER, 
	"FACILITY_ID" NUMBER, 
	"CODE" VARCHAR2(20 BYTE), 
	"DESC_P" VARCHAR2(100 BYTE), 
	"DESC_S" VARCHAR2(100 BYTE), 
	"CLASS_LEVEL" NUMBER(3,0), 
	"IS_DAYCASE" NUMBER(1,0), 
	"IS_DOCTOR_ORDER" NUMBER(1,0), 
	"IS_COMPANION" NUMBER(1,0), 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"IS_ISOLATED" NUMBER(1,0) DEFAULT 0, 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
