--------------------------------------------------------
--  DDL for Table ADT_RESERVATIONS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."ADT_RESERVATIONS" 
   (	"ID" NUMBER, 
	"FACILITY_ID" NUMBER, 
	"RESERVATION_DATE" DATE, 
	"RESERVED_BY" VARCHAR2(100 BYTE), 
	"DOCTOR_ID" NUMBER, 
	"REQUIRED_DATE" DATE, 
	"ADMISSION_REASON_ID" NUMBER, 
	"PATIENT_ID" RAW(32), 
	"DEALING_TYPE" NUMBER(2,0), 
	"STATUS" NUMBER(1,0), 
	"SECTION_ID" NUMBER, 
	"ROOM_ID" NUMBER, 
	"BED_ID" NUMBER, 
	"CLASS_ID" NUMBER, 
	"LENGTH_OF_STAY" NUMBER(3,0), 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"TELEPHONE_NO" VARCHAR2(20 BYTE), 
	"NOTE" VARCHAR2(1000 BYTE), 
	"RESERVED_METHOD" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
