--------------------------------------------------------
--  DDL for Table AUDIT_DDL
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."AUDIT_DDL" 
   (	"D" DATE, 
	"OSUSER" VARCHAR2(255 BYTE), 
	"CURRENT_USER" VARCHAR2(255 BYTE), 
	"HOST" VARCHAR2(255 BYTE), 
	"TERMINAL" VARCHAR2(255 BYTE), 
	"OWNER" VARCHAR2(30 BYTE), 
	"TYPE" VARCHAR2(30 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"SYSEVENT" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
