--------------------------------------------------------
--  DDL for Table CTR_BILL_TYPE_SERIALS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."CTR_BILL_TYPE_SERIALS" 
   (	"ID" NUMBER, 
	"TYPE_ID" NUMBER, 
	"SERIAL_ID" NUMBER, 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
