--------------------------------------------------------
--  DDL for Table CTR_LONG_TEXT
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."CTR_LONG_TEXT" 
   (	"ID" NUMBER, 
	"ACTIVE_IND" NUMBER(4,0), 
	"LONG_TEXT" VARCHAR2(255 BYTE), 
	"PARENT_ENTITY_ID" NUMBER, 
	"PARENT_ENTITY_NAME" VARCHAR2(50 BYTE), 
	"UPDT_CNT" NUMBER, 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"IS_ACTIVE" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
