--------------------------------------------------------
--  DDL for Table CTR_PAGE_AUTHENTICATIONS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."CTR_PAGE_AUTHENTICATIONS" 
   (	"ID" NUMBER, 
	"MENU_ID" NUMBER, 
	"GROUP_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"AUTH_TYPE" NUMBER(1,0), 
	"CAN_ADD" NUMBER(1,0), 
	"CAN_UPDATE" NUMBER(1,0), 
	"CAN_DELETE" NUMBER(1,0), 
	"CAN_SHOW" NUMBER(1,0), 
	"IS_ACTIVE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
