--------------------------------------------------------
--  DDL for Table CTR_CODES
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."CTR_CODES" 
   (	"ID" NUMBER, 
	"GROUP_CODE" VARCHAR2(30 BYTE), 
	"CODE_ID" NUMBER, 
	"DESC_P" VARCHAR2(30 BYTE), 
	"DESC_S" VARCHAR2(30 BYTE), 
	"IS_ACTIVE" NUMBER(1,0), 
	"CAN_DELETE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
