--------------------------------------------------------
--  DDL for Table CTR_ORDER_CATALOG_ITEMS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."CTR_ORDER_CATALOG_ITEMS" 
   (	"ID" NUMBER, 
	"CATALOG_CD" NUMBER(4,0), 
	"ITEM_ID" NUMBER(4,0), 
	"SYNONYM_ID" NUMBER(4,0), 
	"UPDT_CNT" NUMBER(4,0), 
	"MULTUM_DRUG_IDENTIFIER" NUMBER(4,0), 
	"OE_FORMAT_ID" NUMBER(4,0), 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"IS_ACTIVE" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
