--------------------------------------------------------
--  DDL for Table CTR_DOCTOR_CONSULTATIONS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."CTR_DOCTOR_CONSULTATIONS" 
   (	"ID" NUMBER, 
	"FACILITY_ID" NUMBER, 
	"DOCTOR_ID" NUMBER, 
	"CONSULTATION_ID" NUMBER, 
	"ADMISSION_ALLOW" NUMBER(1,0), 
	"IS_EXTERNAL" NUMBER(1,0), 
	"OR_ALLOW" NUMBER(1,0), 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"IS_ACTIVE" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
