--------------------------------------------------------
--  DDL for Table CTR_CODE_VALUE
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."CTR_CODE_VALUE" 
   (	"ID" NUMBER, 
	"ACTIVE_IND" NUMBER(4,0), 
	"BEGIN_EFFECTIVE_DATE_TM" DATE, 
	"CODE_SET" NUMBER, 
	"CODE_VALUE" NUMBER, 
	"DEFINITION" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"DISPLAY" VARCHAR2(200 BYTE), 
	"END_EFFECTIVE_DATE_TM" DATE, 
	"INACTIVE_DATE_TM" DATE, 
	"UPDT_CNT" NUMBER, 
	"FACILITY_ID" NUMBER, 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"IS_ACTIVE" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
