--------------------------------------------------------
--  DDL for Table CTR_FACILITIES
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."CTR_FACILITIES" 
   (	"ID" NUMBER, 
	"CODE" VARCHAR2(20 BYTE), 
	"DESC_P" VARCHAR2(100 BYTE), 
	"DESC_S" VARCHAR2(100 BYTE), 
	"CURR_ID" NUMBER, 
	"IS_MOTHER_COMPANY" NUMBER(1,0), 
	"CITY_ID" NUMBER, 
	"FAX_CODE" VARCHAR2(20 BYTE), 
	"PHONE_CODE" VARCHAR2(20 BYTE), 
	"POSTAL_CODE" VARCHAR2(20 BYTE), 
	"POBOX" VARCHAR2(20 BYTE), 
	"ZIP_CODE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"WEB_SITE" VARCHAR2(100 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"TAX_PROFILE_CODE" VARCHAR2(20 BYTE), 
	"MOBILE_CODE" VARCHAR2(20 BYTE), 
	"IS_LEAF" NUMBER(1,0), 
	"PARENT_ID" NUMBER, 
	"IS_ACTIVE" NUMBER(1,0), 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"COUNTRY_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
