--------------------------------------------------------
--  DDL for Table CTR_STAFF
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."CTR_STAFF" 
   (	"ID" NUMBER, 
	"FACILITY_ID" NUMBER, 
	"STAFF_CODE" VARCHAR2(20 BYTE), 
	"IS_DOCTOR" NUMBER(1,0), 
	"LAST_NAME_P" VARCHAR2(20 BYTE), 
	"LAST_NAME_S" VARCHAR2(20 BYTE), 
	"MID_NAME_P" VARCHAR2(20 BYTE), 
	"MID_NAME_S" VARCHAR2(20 BYTE), 
	"BIRTH_DATE" DATE, 
	"FIRST_NAME_P" VARCHAR2(20 BYTE), 
	"FATHER_NAME_P" VARCHAR2(20 BYTE), 
	"FIRST_NAME_S" VARCHAR2(20 BYTE), 
	"FATHER_NAME_S" VARCHAR2(20 BYTE), 
	"GENDER" NUMBER(1,0), 
	"HEIGHT" NUMBER(3,0), 
	"WEIGHT" NUMBER(3,0), 
	"MARITAL_STATUS" NUMBER(1,0), 
	"BLOOD_GROUP_ID" NUMBER(2,0), 
	"NATIONALITY_ID" NUMBER, 
	"ZIP_CODE" VARCHAR2(10 BYTE), 
	"POBOX" VARCHAR2(10 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"E_MAIL" VARCHAR2(100 BYTE), 
	"HOME_TEL" VARCHAR2(20 BYTE), 
	"WORK_TEL" VARCHAR2(20 BYTE), 
	"MOBILE" VARCHAR2(20 BYTE), 
	"STAFF_IMAGE" VARCHAR2(200 BYTE), 
	"CONTRACT_TYPE" NUMBER(2,0), 
	"PATIENT_ID" RAW(32), 
	"RELIGION_ID" NUMBER, 
	"IS_CITIZENSHIP" NUMBER(1,0), 
	"SECTION_ID" NUMBER, 
	"JOB_CODE" VARCHAR2(20 BYTE), 
	"CONTRACT_CODE" VARCHAR2(20 BYTE), 
	"STATUS" NUMBER(1,0), 
	"BEGIN_WORK_DATE" DATE, 
	"BEGIN_DATE" DATE, 
	"END_DATE" DATE, 
	"NATIONAL_CODE" VARCHAR2(100 BYTE), 
	"NICKNAME_P" VARCHAR2(20 BYTE), 
	"NICKNAME_S" VARCHAR2(20 BYTE), 
	"OFFICE_CODE" VARCHAR2(10 BYTE), 
	"OFFICE_PHONE" VARCHAR2(10 BYTE), 
	"OFFICE_EMAIL" VARCHAR2(10 BYTE), 
	"EXPIRY_DATE" DATE, 
	"IS_BLACK_LIST" NUMBER(1,0), 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"IS_ADMISSION_ALLOWED" NUMBER(1,0), 
	"USER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
