--------------------------------------------------------
--  DDL for Table CTR_ORG_STORES
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."CTR_ORG_STORES" 
   (	"ID" NUMBER, 
	"FACILITY_ID" NUMBER, 
	"CODE" VARCHAR2(20 BYTE), 
	"DESC_P" VARCHAR2(200 BYTE), 
	"DESC_S" VARCHAR2(200 BYTE), 
	"PARENT_ID" NUMBER, 
	"IS_LEAF" NUMBER(1,0), 
	"IS_ACTIVE" NUMBER(1,0), 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"NOTE" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
