--------------------------------------------------------
--  DDL for Table CTR_TRIAGE_CODES
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."CTR_TRIAGE_CODES" 
   (	"ID" NUMBER, 
	"MAIN_CATEGORY" VARCHAR2(50 BYTE), 
	"SUB_CATEGORY" VARCHAR2(50 BYTE), 
	"DESC_P" NVARCHAR2(100), 
	"DESC_S" NVARCHAR2(100), 
	"SCORE" NUMBER(2,0), 
	"SETTING" NVARCHAR2(100), 
	"IS_ACTIVE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
