--------------------------------------------------------
--  DDL for Table CTR_COUNTRIES
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."CTR_COUNTRIES" 
   (	"ID" NUMBER, 
	"FACILITY_ID" NUMBER, 
	"DESC_P" VARCHAR2(50 BYTE), 
	"DESC_S" VARCHAR2(50 BYTE), 
	"NATIONALITY_P" VARCHAR2(100 BYTE), 
	"NATIONALITY_S" VARCHAR2(100 BYTE), 
	"KEY" VARCHAR2(10 BYTE), 
	"RELIGION_ID" NUMBER, 
	"IS_RESTRICTED" NUMBER(1,0), 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"CURRENCY_ID" NUMBER, 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
