--------------------------------------------------------
--  DDL for Table CTR_YEAR_MONTHS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."CTR_YEAR_MONTHS" 
   (	"ID" NUMBER, 
	"MONTH_CODE" VARCHAR2(10 BYTE), 
	"MONTH_DESC_P" VARCHAR2(10 BYTE), 
	"MONTH_DESC_S" VARCHAR2(10 BYTE), 
	"HIJRIH_P" VARCHAR2(10 BYTE), 
	"HIJRIH_S" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 131072 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
