--------------------------------------------------------
--  DDL for Table CTR_MENUS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."CTR_MENUS" 
   (	"ID" NUMBER, 
	"PARENT_ID" NUMBER, 
	"NODE_NAME_P" VARCHAR2(50 BYTE), 
	"NODE_NAME_S" VARCHAR2(50 BYTE), 
	"NODE_ICON" VARCHAR2(500 BYTE), 
	"NODE_LEVEL" NUMBER(2,0), 
	"IS_PAGE" NUMBER(1,0), 
	"PAGE_PATH" VARCHAR2(200 BYTE), 
	"NODE_ORDER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
