--------------------------------------------------------
--  DDL for Table CTR_MEDICAL_SECTIONS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."CTR_MEDICAL_SECTIONS" 
   (	"ID" NUMBER, 
	"SECTION_ID" NUMBER, 
	"CATEGORY_ID" NUMBER, 
	"IS_REGISTRATION" NUMBER(1,0), 
	"IS_ORDER_SECTION" NUMBER(1,0), 
	"PATIENT_TYPE_ID" NUMBER(1,0), 
	"CREATED_BY" NUMBER, 
	"CRAETED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"IS_SCHEDULE" NUMBER(1,0), 
	"IS_SERVICE_SECTION" NUMBER(1,0), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
