--------------------------------------------------------
--  DDL for Table CTR_CITIES
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."CTR_CITIES" 
   (	"ID" NUMBER, 
	"FACILITY_ID" NUMBER, 
	"COUNTRY_ID" NUMBER, 
	"DESC_P" VARCHAR2(100 BYTE), 
	"DESC_S" VARCHAR2(100 BYTE), 
	"PHONE_KEY" VARCHAR2(100 BYTE), 
	"ZONE_CODE" VARCHAR2(20 BYTE), 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT NULL, 
	"CONCURRENCY_FLAG" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
