--------------------------------------------------------
--  DDL for Table CTR_WEEK_DAYS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."CTR_WEEK_DAYS" 
   (	"ID" NUMBER, 
	"DAY_CODE" VARCHAR2(10 BYTE), 
	"DAY_DESC_P" VARCHAR2(10 BYTE), 
	"DAY_DESC_S" VARCHAR2(10 BYTE), 
	"SHORT_CUT_P" VARCHAR2(10 BYTE), 
	"SHORT_CUT_S" VARCHAR2(10 BYTE), 
	"IS_WEEKEND" NUMBER(1,0), 
	"DAY_OR" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 131072 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
