--------------------------------------------------------
--  DDL for Table EMPLOYEETEST993847
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."EMPLOYEETEST993847" 
   (	"ID" NUMBER(20,0), 
	"NAME" NVARCHAR2(255), 
	"SALARY" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
