--------------------------------------------------------
--  DDL for Table ER_TRIAGE_DOCUMENTATIONS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."ER_TRIAGE_DOCUMENTATIONS" 
   (	"ID" NUMBER, 
	"PATIENT_ID" RAW(32), 
	"VISIT_ID" NUMBER, 
	"ARRIVAL_TIME" DATE, 
	"AGE" NUMBER(3,0), 
	"GENDER" NUMBER(1,0), 
	"NATIONALITY_ID" NUMBER, 
	"TELEPHONE" VARCHAR2(50 BYTE), 
	"TRIAGE_CATEGORY" NUMBER(2,0), 
	"ALLERGIES" NVARCHAR2(50), 
	"MODE_OF_ARRIVAL" NUMBER(2,0), 
	"CHIEF_COMPLAINT" NUMBER, 
	"OTHER_CHIEF_COMPLAINT" NVARCHAR2(150), 
	"GROUP_CODE" VARCHAR2(50 BYTE), 
	"COPD" NUMBER(1,0), 
	"IMMUNOSUPPRESSION" NUMBER(1,0), 
	"CARDIAC" NUMBER(1,0), 
	"HTN" NUMBER(1,0), 
	"CVA" NUMBER(1,0), 
	"SMOKER" NUMBER(1,0), 
	"SEIZURES" NUMBER(1,0), 
	"DIABETES" NUMBER(1,0), 
	"CHF" NUMBER(1,0), 
	"CANCER" NUMBER(1,0), 
	"TB" NUMBER(1,0), 
	"OTHER_SIGNIFICANT_MEDIACAL" NVARCHAR2(150), 
	"B_P" NVARCHAR2(50), 
	"TEMP" NVARCHAR2(50), 
	"PULSE" NVARCHAR2(50), 
	"RESP" NVARCHAR2(50), 
	"O2_SAT" NVARCHAR2(50), 
	"PAIN" NVARCHAR2(50), 
	"NURSE_ID" NUMBER, 
	"DOCTOR_ID" NUMBER, 
	"NURSING_ASSESSMENT_DATE" DATE, 
	"HEIGHT" VARCHAR2(10 BYTE), 
	"WEIGHT" VARCHAR2(10 BYTE), 
	"ACTUAL" NVARCHAR2(50), 
	"STATED" NVARCHAR2(50), 
	"LNMP" NVARCHAR2(50), 
	"GRAV" NVARCHAR2(50), 
	"PARA" NVARCHAR2(50), 
	"AB" NVARCHAR2(50), 
	"PREGNANT" NVARCHAR2(50), 
	"EDD" NVARCHAR2(50), 
	"N_A" NVARCHAR2(50), 
	"TRIAGE_DATE" DATE, 
	"ASTHMA" NUMBER(1,0), 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
