--------------------------------------------------------
--  DDL for Table INS_GUARANTOR_VALIDLISTS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."INS_GUARANTOR_VALIDLISTS" 
   (	"ID" NUMBER, 
	"GUARANTOR_ID" NUMBER, 
	"SUBSCRIBER_CODE" VARCHAR2(20 CHAR), 
	"SUBSCRIBER_NAME" VARCHAR2(100 CHAR), 
	"IS_BLACK_LIST" NUMBER(1,0), 
	"SUBSCRIBER_NAME_S" VARCHAR2(100 CHAR), 
	"CLASS_CODE" NUMBER, 
	"VALIDLIST_SERIAL" NUMBER, 
	"PARENT_SUBSCRIBER_CODE" VARCHAR2(20 CHAR), 
	"PATIENT_ID" RAW(32), 
	"RELATIONSHIP_CODE" NUMBER, 
	"VALIDATE_DATE" DATE, 
	"BADGE_NO" VARCHAR2(10 CHAR), 
	"ADDITIONAL_DATE" DATE, 
	"BIRTH_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"STATUS" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 131072 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
