--------------------------------------------------------
--  DDL for Table INS_GUARANTOR_CONTRACTS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."INS_GUARANTOR_CONTRACTS" 
   (	"ID" NUMBER, 
	"GUARANTOR_ID" NUMBER, 
	"CONTRACT_NO" NUMBER, 
	"IS_PREEXIST_COVERED" NUMBER(1,0), 
	"IS_CHRONIC_COVERED" NUMBER(1,0), 
	"NOTES" VARCHAR2(3500 CHAR), 
	"STATUS" NUMBER(1,0), 
	"TYPE_ID" NUMBER, 
	"CLASS_ID" NUMBER, 
	"IS_AUTO" NUMBER(1,0) DEFAULT NULL, 
	"IN_SUBSCRIBER" NUMBER(3,0), 
	"OUT_SUBSCRIBER" NUMBER(3,0), 
	"IN_BENEFICIARY" NUMBER(3,0), 
	"OUT_BENEFICIARY" NUMBER(3,0), 
	"ACCOMMODATION_CLASS_ID" NUMBER, 
	"DISCOUNT_TYPE_ID" NUMBER, 
	"FOLLOW_UP_SESSION" NUMBER(3,0), 
	"TRANSFER_SESSION" NUMBER(3,0), 
	"IS_UNIQUE_BADGE" NUMBER(1,0) DEFAULT NULL, 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"FACILITY_ID" NUMBER DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
