--------------------------------------------------------
--  DDL for Table INS_PACKAGE_DTL
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."INS_PACKAGE_DTL" 
   (	"ID" NUMBER, 
	"PKG_NO" NUMBER, 
	"UPPER_LIMIT" NUMBER, 
	"NO_TIMES" NUMBER, 
	"ITEM_NO" NUMBER, 
	"REMARKS" VARCHAR2(200 CHAR), 
	"ESTIMATED_COST" NUMBER, 
	"IS_DISCHARGE_PRESCRIPTION" NUMBER(1,0), 
	"PATIENT_TYPE" NUMBER, 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"STATUS" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 131072 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
