--------------------------------------------------------
--  DDL for Table INS_EXCLUDED_SERVICES
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."INS_EXCLUDED_SERVICES" 
   (	"ID" NUMBER, 
	"GUARANTOR_ID" NUMBER, 
	"CLASS_ID" NUMBER, 
	"ITEM_ID" NUMBER, 
	"PATIENT_TYPE_ID" NUMBER, 
	"CONTRACT_NO" NUMBER, 
	"NOT_EXCLUDED" NUMBER(1,0), 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"STATUS" NUMBER(1,0), 
	"FACILITY_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
