--------------------------------------------------------
--  DDL for Table INS_GUARANTOR_CLASSES
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."INS_GUARANTOR_CLASSES" 
   (	"ID" NUMBER, 
	"GUARANTOR_ID" NUMBER, 
	"CODE" NUMBER, 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"STATUS" NUMBER(1,0) DEFAULT NULL, 
	"FACILITY_ID" NUMBER DEFAULT NULL, 
	"DESC_P" VARCHAR2(200 BYTE), 
	"DESC_S" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
