--------------------------------------------------------
--  DDL for Table INS_PACKAGE_DESCRIPTIONS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."INS_PACKAGE_DESCRIPTIONS" 
   (	"ID" NUMBER, 
	"PCKG_NO" NUMBER, 
	"PCKG_DESCR" VARCHAR2(100 CHAR), 
	"PCKG_DETAIL" VARCHAR2(4000 CHAR), 
	"PCKG_DESCR_S" VARCHAR2(100 CHAR), 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"STATUS" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 131072 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
