--------------------------------------------------------
--  DDL for Table INS_DEDUCTIBLES
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."INS_DEDUCTIBLES" 
   (	"ID" NUMBER, 
	"GUARANTOR_ID" NUMBER, 
	"CLASS_ID" NUMBER, 
	"CONTRACT_NO" NUMBER, 
	"SECTION_NO" NUMBER, 
	"CONSULTATION_AMT" NUMBER, 
	"SERVICE_AMT" NUMBER, 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"STATUS" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 131072 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
