--------------------------------------------------------
--  DDL for Table INS_PREAPPROVAL_DIAGNOSIS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."INS_PREAPPROVAL_DIAGNOSIS" 
   (	"ID" NUMBER, 
	"SERIAL_NO" NUMBER, 
	"ITEM_NO" NUMBER, 
	"AUTO" NUMBER, 
	"IS_AUTOAPPROVAL_SENT" NUMBER(1,0), 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"STATUS" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 131072 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
