--------------------------------------------------------
--  Constraints for Table LAB_LOCATION_HIRARICHY
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."LAB_LOCATION_HIRARICHY" ADD CONSTRAINT "LAB_LOCATION_HIRARICHY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."LAB_LOCATION_HIRARICHY" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_LOCATION_HIRARICHY" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_LOCATION_HIRARICHY" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_LOCATION_HIRARICHY" MODIFY ("H_CHILD_LOC_TYPE_LGC" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_LOCATION_HIRARICHY" MODIFY ("H_CHILD_LOC_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_LOCATION_HIRARICHY" MODIFY ("H_PARENT_LOC_TYPE_LGC" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_LOCATION_HIRARICHY" MODIFY ("H_PARENT_LOC_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_LOCATION_HIRARICHY" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_LOCATION_HIRARICHY" MODIFY ("ID" NOT NULL ENABLE);
