--------------------------------------------------------
--  Constraints for Table LAB_GENERAL_CODE
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."LAB_GENERAL_CODE" ADD CONSTRAINT "LAB_GENERAL_CODE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."LAB_GENERAL_CODE" MODIFY ("IS_LOCATION" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_GENERAL_CODE" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_GENERAL_CODE" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_GENERAL_CODE" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_GENERAL_CODE" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_GENERAL_CODE" MODIFY ("DESC_S" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_GENERAL_CODE" MODIFY ("DESC_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_GENERAL_CODE" MODIFY ("DISPLAY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_GENERAL_CODE" MODIFY ("CODE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_GENERAL_CODE" MODIFY ("GROUP_CODE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_GENERAL_CODE" MODIFY ("ID" NOT NULL ENABLE);
