--------------------------------------------------------
--  Constraints for Table LAB_ACCESSION_CLASS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."LAB_ACCESSION_CLASS" ADD CONSTRAINT "LAB_ACCESSION_CLASS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."LAB_ACCESSION_CLASS" MODIFY ("DESC_S" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ACCESSION_CLASS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ACCESSION_CLASS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ACCESSION_CLASS" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ACCESSION_CLASS" MODIFY ("ACC_INCREMENT_VALUE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ACCESSION_CLASS" MODIFY ("ACC_PARTS_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ACCESSION_CLASS" MODIFY ("DISPLAY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ACCESSION_CLASS" MODIFY ("DESC_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ACCESSION_CLASS" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ACCESSION_CLASS" MODIFY ("ID" NOT NULL ENABLE);
