--------------------------------------------------------
--  Constraints for Table LAB_QC_LOT_DEFINITION
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."LAB_QC_LOT_DEFINITION" ADD CONSTRAINT "LAB_QC_LOT_DEFINETION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."LAB_QC_LOT_DEFINITION" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_QC_LOT_DEFINITION" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_QC_LOT_DEFINITION" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_QC_LOT_DEFINITION" MODIFY ("DESC_S" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_QC_LOT_DEFINITION" MODIFY ("END_EFFECTIVE_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_QC_LOT_DEFINITION" MODIFY ("BEGIN_EFFECTIVE_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_QC_LOT_DEFINITION" MODIFY ("EXPIRY_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_QC_LOT_DEFINITION" MODIFY ("STATUS_LGC" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_QC_LOT_DEFINITION" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_QC_LOT_DEFINITION" MODIFY ("KIT_DEFINITION_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_QC_LOT_DEFINITION" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_QC_LOT_DEFINITION" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_QC_LOT_DEFINITION" MODIFY ("MANUFACTER_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_QC_LOT_DEFINITION" MODIFY ("DESC_P" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_QC_LOT_DEFINITION" MODIFY ("DISPLAY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_QC_LOT_DEFINITION" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_QC_LOT_DEFINITION" MODIFY ("ID" NOT NULL ENABLE);
