--------------------------------------------------------
--  Constraints for Table LAB_ALPHA_REFERENCE_RANGE
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."LAB_ALPHA_REFERENCE_RANGE" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ALPHA_REFERENCE_RANGE" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ALPHA_REFERENCE_RANGE" MODIFY ("RF_TYPE_LGC" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ALPHA_REFERENCE_RANGE" MODIFY ("PAR_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ALPHA_REFERENCE_RANGE" MODIFY ("RF_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ALPHA_REFERENCE_RANGE" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."LAB_ALPHA_REFERENCE_RANGE" MODIFY ("ID" NOT NULL ENABLE);
