--------------------------------------------------------
--  DDL for Table OPS_PATIENT_VISITS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."OPS_PATIENT_VISITS" 
   (	"ID" NUMBER, 
	"SECTION_ID" NUMBER, 
	"VISIT_NO" NUMBER(4,0), 
	"FACILITY_ID" NUMBER, 
	"PATIENT_ID" RAW(32), 
	"DEALING_TYPE" NUMBER(1,0), 
	"PARTY_ID" NUMBER, 
	"REFERNCE_ID" NUMBER, 
	"DOCTOR_ID" NUMBER, 
	"VISIT_DATE" DATE, 
	"STATUS" NUMBER(1,0), 
	"DISCHARGE_STATUS" NUMBER(1,0), 
	"DISCHARGE_DATE" DATE, 
	"REMARKS" VARCHAR2(2000 BYTE), 
	"USER_ID" NUMBER, 
	"PC_NAME" VARCHAR2(40 BYTE), 
	"ENTRY_DATE" DATE, 
	"COMPLAIN_ID" NUMBER, 
	"TEL_TYPE" NUMBER(2,0), 
	"TEL_NO" VARCHAR2(30 BYTE), 
	"IS_ER_CASE" NUMBER(1,0), 
	"ACCIDENT_ID" NUMBER, 
	"IS_POLICE_CASE" NUMBER(1,0), 
	"DISCHARGE_DOCTOR" NUMBER, 
	"DISCHARGE_PARTY_ID" NUMBER, 
	"DISCHARGE_REFERANCE_ID" NUMBER, 
	"APPT_ID" NUMBER(15,0), 
	"CRISIS_ID" NUMBER, 
	"JUDICIAL_DISCHARGE_STATUS" NUMBER(1,0), 
	"ATTEND_NO" NUMBER(6,0), 
	"DISCHARGE_BY" NUMBER, 
	"DISCHARGE_PC" VARCHAR2(70 BYTE), 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"EXTERNAL_DOCTOR" VARCHAR2(200 BYTE), 
	"EXAMINATION_REASON" VARCHAR2(1000 BYTE), 
	"CANCEL_REASON" VARCHAR2(400 BYTE), 
	"CANCELLATION_DATE" DATE, 
	"CANCELLATION_BY" NUMBER, 
	"ER_AREA_ID" NUMBER, 
	"POLICE_CASE_NOTE" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
