--------------------------------------------------------
--  DDL for Table OPS_VITAL_SIGNS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."OPS_VITAL_SIGNS" 
   (	"ID" NUMBER, 
	"VISIT_ID" NUMBER, 
	"PATIENT_ID" RAW(32), 
	"TIME" DATE, 
	"TEMP" NVARCHAR2(20), 
	"PULSE" NVARCHAR2(20), 
	"RESP" NVARCHAR2(20), 
	"B_P" NVARCHAR2(20), 
	"O2_SAT" NVARCHAR2(20), 
	"PAIN" NVARCHAR2(20), 
	"INTERVENTION" NVARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
