--------------------------------------------------------
--  DDL for Table OPS_ER_AREAS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."OPS_ER_AREAS" 
   (	"ID" NUMBER, 
	"DESC_S" VARCHAR2(50 BYTE), 
	"DESC_P" VARCHAR2(50 BYTE), 
	"AREA_CODE" VARCHAR2(10 BYTE), 
	"BED_COUNTS" NUMBER(2,0), 
	"STATUS" NUMBER(1,0), 
	"NOTES" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
