--------------------------------------------------------
--  DDL for Table ORD_ORDERS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."ORD_ORDERS" 
   (	"ACTIVE_IND" NUMBER(4,0), 
	"ACTIVITY_TYPE_CD" NUMBER(4,0), 
	"CATALOG_CD" NUMBER(4,0), 
	"CATALOG_TYPE_CD" NUMBER(4,0), 
	"CONTRIBUTOR_SYSTEM_CD" NUMBER(4,0), 
	"ENCOUNTER_ID" NUMBER(4,0), 
	"ENCNTR_FINANCIAL_ID" NUMBER(4,0), 
	"FACILITY_ID" NUMBER(4,0), 
	"FREQUENCY_ID" NUMBER(4,0), 
	"IV_IND" NUMBER(4,0), 
	"MED_ORDER_TYPE_CD" NUMBER(4,0), 
	"OE_FORMAT_ID" NUMBER(4,0), 
	"ORDER_COMMENT_IND" NUMBER(4,0), 
	"ORDER_DETAIL_DISPLAY_LINE" VARCHAR2(200 BYTE), 
	"ORDER_ID" NUMBER(4,0), 
	"ORDER_MNEMONIC" VARCHAR2(200 BYTE), 
	"ORDER_STATUS_CD" NUMBER(4,0), 
	"PERSON_ID" NUMBER(4,0), 
	"PRN_IND" NUMBER(4,0), 
	"PRODUCT_ID" NUMBER(4,0), 
	"STOP_TYPE_CD" NUMBER(4,0), 
	"ORDER_TREATING_PHY_ID" NUMBER(4,0), 
	"INV_SECTION_ID" NUMBER(4,0), 
	"PRIORITY_LGC" NUMBER(4,0), 
	"ORDER_DATE" DATE, 
	"ORDER_START_EFFICTIVE_DATE" DATE, 
	"ORDER_END_EFFICTIVE_DATE" DATE, 
	"ORDER_CS_ID" NUMBER(4,0), 
	"ORDER_COMMENT_ID" VARCHAR2(200 BYTE), 
	"ORDER_CANCEL_REASON_LGC" NUMBER(4,0), 
	"ORDER_CANCEL_ID" NUMBER(4,0), 
	"ORDER_CANCEL_DATE" DATE, 
	"ORDER_COMPLETE_DATE" DATE, 
	"ORDER_COMPLETE_ID" NUMBER(4,0), 
	"CREATE_DATE" DATE, 
	"CREATE_ID" NUMBER(4,0), 
	"UPDT_CNT" NUMBER(4,0), 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" NUMBER(4,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 131072 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
