--------------------------------------------------------
--  Constraints for Table ORD_ORDER_ACTIONS
--------------------------------------------------------

  ALTER TABLE "HISRHAMZEH"."ORD_ORDER_ACTIONS" ADD CONSTRAINT "ORD_ORDER_ACTIONS_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HISRHAMZEH"."ORD_ORDER_ACTIONS" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDER_ACTIONS" MODIFY ("UPDT_CNT" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDER_ACTIONS" MODIFY ("STOP_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDER_ACTIONS" MODIFY ("ORDER_TZ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDER_ACTIONS" MODIFY ("ORDER_STATUS_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDER_ACTIONS" MODIFY ("ORDER_PROVIDER_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDER_ACTIONS" MODIFY ("ORDER_LOCN_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDER_ACTIONS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDER_ACTIONS" MODIFY ("ORDER_DT_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDER_ACTIONS" MODIFY ("ORDER_ACTION_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDER_ACTIONS" MODIFY ("NEXT_DOSE_DT_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDER_ACTIONS" MODIFY ("NEEDS_VERIFY_IND" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDER_ACTIONS" MODIFY ("FREQUENCY_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDER_ACTIONS" MODIFY ("EFFECTIVE_TZ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDER_ACTIONS" MODIFY ("EFFECTIVE_DT_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDER_ACTIONS" MODIFY ("CURRENT_START_TZ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDER_ACTIONS" MODIFY ("CURRENT_START_DT_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDER_ACTIONS" MODIFY ("COMMUNICATION_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDER_ACTIONS" MODIFY ("ACTION_TZ" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDER_ACTIONS" MODIFY ("ACTION_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDER_ACTIONS" MODIFY ("ACTION_SEQUENCE" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDER_ACTIONS" MODIFY ("ACTION_REJECTED_IND" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDER_ACTIONS" MODIFY ("ACTION_PERSONNEL_ID" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDER_ACTIONS" MODIFY ("ACTION_INITIATED_DATE_TM" NOT NULL ENABLE);
  ALTER TABLE "HISRHAMZEH"."ORD_ORDER_ACTIONS" MODIFY ("ACTION_DATE_TM" NOT NULL ENABLE);
