--------------------------------------------------------
--  DDL for Table OT_OPERATING_ROOM
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."OT_OPERATING_ROOM" 
   (	"ID" NUMBER, 
	"FACILITY_ID" NUMBER, 
	"ROOM_CODE" VARCHAR2(50 BYTE), 
	"TYPE" VARCHAR2(50 BYTE), 
	"DESC_LONG" VARCHAR2(500 BYTE), 
	"DESC_S" VARCHAR2(100 BYTE), 
	"DESC_P" VARCHAR2(100 BYTE), 
	"RESTRICTED_BY_SPECIALITY" NUMBER(1,0), 
	"OVERBOOKING_ALLOWED" NUMBER(1,0), 
	"WORKING_DAY_START_TIME" DATE, 
	"WORKING_DAY_END_TIME" DATE, 
	"HOLIDAY_START_TIME" DATE, 
	"HOLIDAY_END_TIME" DATE, 
	"CHARGEABLE_ROOM" NUMBER(1,0), 
	"DEFAULT_RECOVERY_ROOM_CODE" NUMBER, 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 131072 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
