--------------------------------------------------------
--  DDL for Table OT_OPERATION
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."OT_OPERATION" 
   (	"ID" NUMBER, 
	"FACILITY_ID" NUMBER, 
	"ICD_CODE" NUMBER, 
	"CPT_CODE" NUMBER, 
	"DESC_LONG" VARCHAR2(500 BYTE), 
	"DESC_P" VARCHAR2(100 BYTE), 
	"DESC_S" VARCHAR2(100 BYTE), 
	"SPECIALITY_ID" NUMBER, 
	"DURATION" NUMBER(2,0), 
	"AVG_DURATION" NUMBER(2,0), 
	"SIDE_APPLICABLE" NUMBER(1,0), 
	"OPERATION_TYPE" NUMBER, 
	"IS_ACTIVE" NUMBER(1,0), 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 131072 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
