--------------------------------------------------------
--  DDL for Table OT_ROOM_STORE
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."OT_ROOM_STORE" 
   (	"ID" NUMBER, 
	"FACILITY_ID" NUMBER, 
	"ROOM_ID" NUMBER, 
	"DEFAULT_STORE_ID" NUMBER, 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"IS_ACTIVE" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 131072 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
