--------------------------------------------------------
--  DDL for Table OT_SURGERY_TYPE
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."OT_SURGERY_TYPE" 
   (	"ID" NUMBER, 
	"CODE" VARCHAR2(50 BYTE), 
	"DESC_LONG" VARCHAR2(500 BYTE), 
	"DESC_S" VARCHAR2(100 BYTE), 
	"DESC_P" VARCHAR2(100 BYTE), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"TYPE" VARCHAR2(50 BYTE), 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"FACILITY_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 131072 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
