--------------------------------------------------------
--  DDL for Table OT_TRANSACTIONS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."OT_TRANSACTIONS" 
   (	"ID" NUMBER, 
	"VISIT_NUMBER" NUMBER, 
	"PATIENT_ID" RAW(32), 
	"CURRENT_STATUS" VARCHAR2(50 BYTE), 
	"OPERATING_ROOM_ID" NUMBER, 
	"CURRENT_LOCATION" VARCHAR2(50 BYTE), 
	"BOOKING_ID" NUMBER, 
	"OT_ORDER" NUMBER, 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"FACILITY_ID" NUMBER, 
	"IS_ACTIVE" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 131072 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
