--------------------------------------------------------
--  DDL for Table PAS_ADT_ELEMENTS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."PAS_ADT_ELEMENTS" 
   (	"ID" NUMBER, 
	"GUARANTOR_ID" NUMBER(6,0), 
	"PATIENT_ID" RAW(32), 
	"ADMISSION_NO" NUMBER(3,0), 
	"ELEMENT_CODE" NUMBER(3,0), 
	"TOTAL" NUMBER(15,3), 
	"TOTAL_EXCL" NUMBER(10,3), 
	"TOTAL_CONT_DISC" NUMBER(10,3), 
	"CONT_DISC_EXCL" NUMBER(10,3), 
	"TOTAL_CASH_DISC" NUMBER(10,3), 
	"CASH_DISC_EXCL" NUMBER(10,3), 
	"TOTAL_PACKAGE_DISC" NUMBER(1,0), 
	"CREATED_BY" NUMBER(4,0), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER(4,0), 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 131072 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
