--------------------------------------------------------
--  DDL for Table PAS_ADT_GUARANTORS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."PAS_ADT_GUARANTORS" 
   (	"ID" NUMBER, 
	"PATIENT_ID" RAW(32), 
	"GUARANTOR_ID" NUMBER, 
	"CLASS_CODE" NUMBER, 
	"ADMISSION_ID" NUMBER, 
	"CONTRACT_NO" NUMBER, 
	"SUBSCRIBER_NO" VARCHAR2(20 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"PRIORITY" NUMBER(1,0), 
	"INSURANCE_TYPE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE, 
	"STATUS" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
