--------------------------------------------------------
--  DDL for Table PAS_OPS_STATEMENTS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."PAS_OPS_STATEMENTS" 
   (	"ID" NUMBER, 
	"SECTION_ID" NUMBER, 
	"PATIENT_VISIT_ID" NUMBER, 
	"PATIENT_ID" RAW(32), 
	"ISSUE_DATE" DATE, 
	"CLOSE_DATE" DATE, 
	"STATUS" NUMBER(1,0), 
	"DEPOSIT" NUMBER(10,3), 
	"TOTAL" NUMBER(10,3), 
	"TOTAL_COVG" NUMBER(10,3), 
	"TOTAL_COVG_CONT_DISC" NUMBER(10,3), 
	"TOTAL_CASH_DISC" NUMBER(10,3), 
	"TOTAL_PACKAGE_DISC" NUMBER(10,3), 
	"PACKAGE_COVG_DISC" NUMBER(10,3), 
	"NEED_CALCULATE" NUMBER(1,0) DEFAULT 0, 
	"ENTRY_DATE" DATE, 
	"USER_ID" NUMBER, 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
