--------------------------------------------------------
--  DDL for Table PAS_PATIENT_GUARANTORS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."PAS_PATIENT_GUARANTORS" 
   (	"ID" NUMBER, 
	"PATIENT_ID" RAW(32), 
	"GUARANTOR_ID" NUMBER, 
	"CLASS_CODE" NUMBER, 
	"SUBSCRIBER_NO" VARCHAR2(20 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"INSURANCE_TYPE" NUMBER DEFAULT 1, 
	"PRIORITY" NUMBER(1,0) DEFAULT 1, 
	"CONTRACT_NO" NUMBER, 
	"INSURE_COVERAGE_CLASS" NUMBER, 
	"CREATED_BY" NUMBER(4,0), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER(4,0), 
	"MODIFIED_DATE" DATE, 
	"STATUS" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
