--------------------------------------------------------
--  DDL for Table PHR_ORDER_CATALOG_SYNONYM
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."PHR_ORDER_CATALOG_SYNONYM" 
   (	"ACTIVE_IND" NUMBER(2,0), 
	"MULTUM_DRUG_IDENTIFIER" VARCHAR2(50 BYTE), 
	"ACTIVITY_TYPE_CD" NUMBER(4,0), 
	"CATALOG_CD" NUMBER(4,0), 
	"CATALOG_TYPE_CD" NUMBER(4,0), 
	"DCP_CLIN_CAT_CD" NUMBER(4,0), 
	"HIDE_FLAG" NUMBER(2,0), 
	"HIGH_ALERT_IND" NUMBER(2,0), 
	"HIGH_ALERT_LONG_TEXT_ID" NUMBER(4,0), 
	"ITEM_ID" NUMBER(4,0), 
	"MNEMONIC" VARCHAR2(255 BYTE), 
	"MNEMONIC_TYPE_CD" NUMBER(4,0), 
	"MULTIPLE_ORD_SENT_IND" NUMBER(2,0), 
	"OE_FORMAT_ID" NUMBER(4,0), 
	"ORDERABLE_TYPE_FLAG" NUMBER(2,0), 
	"ORDER_SENTENCE_ID" NUMBER(4,0), 
	"SYNONYM_ID" NUMBER(4,0), 
	"UPDT_CNT" NUMBER(4,0), 
	"CREATED_BY" NUMBER(4,0), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER(4,0), 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
