--------------------------------------------------------
--  DDL for Table PHR_FREQUENCY_SCHEDULE
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."PHR_FREQUENCY_SCHEDULE" 
   (	"FREQUENCY_ID" NUMBER(4,0), 
	"FREQUENCY_CD" NUMBER(4,0), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"FREQUENCY_TYPE" NUMBER(4,0), 
	"ACTIVE_IND" NUMBER(4,0), 
	"UPDT_CNT" NUMBER(4,0), 
	"PRN_DEFAULT_IND" NUMBER(4,0), 
	"FACILITY_CD" NUMBER(4,0), 
	"EFFECTIVE_DATE_TM" DATE, 
	"CREATED_BY" NUMBER(4,0), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER(4,0), 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
