--------------------------------------------------------
--  DDL for Table PHR_WORKFLOW_ACTION_LOGS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."PHR_WORKFLOW_ACTION_LOGS" 
   (	"WORKFLOW_EVENT_HX_ID" NUMBER(4,0), 
	"WORKFLOW_EVENT_ID" NUMBER(4,0), 
	"WORKFLOW_CD" NUMBER(4,0), 
	"WORKFLOW_STS_CD" NUMBER(4,0), 
	"UPDT_CNT" NUMBER(4,0), 
	"UPDT_TZ" NUMBER(4,0), 
	"CREATED_BY" NUMBER(4,0), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER(4,0), 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
