--------------------------------------------------------
--  DDL for Table PHR_FILL_CYCLE
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."PHR_FILL_CYCLE" 
   (	"FILL_CYCLE_ID" NUMBER(4,0), 
	"LOCATION_CD" NUMBER(4,0), 
	"DISPENSE_CATEGORY_CD" NUMBER(4,0), 
	"FROM_DATE_TM" DATE, 
	"TO_DATE_TM" DATE, 
	"LAST_OPERATION_FLAG" NUMBER(2,0), 
	"UPDT_CNT" NUMBER(4,0), 
	"FROM_TZ" NUMBER(4,0), 
	"TO_TZ" NUMBER(4,0), 
	"CREATED_BY" NUMBER(4,0), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER(4,0), 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
