--------------------------------------------------------
--  DDL for Table PHR_MEDICATION_INVENTORY
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."PHR_MEDICATION_INVENTORY" 
   (	"ID" NUMBER, 
	"LOCATION_ID" NUMBER, 
	"LOCATION_TYPE_CD" NUMBER, 
	"MEDICATION_ID" NUMBER, 
	"IS_ACTIVE" NUMBER(1,0), 
	"UPDATE_COUNT" NUMBER(4,0), 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
