--------------------------------------------------------
--  DDL for Table PHR_DISPENSE_CAT
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."PHR_DISPENSE_CAT" 
   (	"DISPENSE_CATEGORY_CD" NUMBER(4,0), 
	"PRICE_SCHED_ID" NUMBER(4,0), 
	"ORDER_TYPE_FLAG" NUMBER(2,0), 
	"LABEL_FORMAT_CD" NUMBER(4,0), 
	"UPDT_CNT" NUMBER(4,0), 
	"UPDT_TASK" NUMBER(4,0), 
	"PHARM_TYPE_CD" FLOAT(8), 
	"ACTIVE_IND" NUMBER(2,0), 
	"CREATED_BY" NUMBER(4,0), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER(4,0), 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
