--------------------------------------------------------
--  DDL for Table PHR_MED_MANIFACTURING_DETAILS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."PHR_MED_MANIFACTURING_DETAILS" 
   (	"ID" NUMBER, 
	"AWP" FLOAT(126), 
	"COST1" FLOAT(126), 
	"COST2" FLOAT(126), 
	"BRAND_IND" NUMBER, 
	"UNIT_DOSE_IND" NUMBER(1,0), 
	"MANUFACTURER_CD" NUMBER, 
	"INNER_PACKAGE_TYPE_ID" NUMBER, 
	"OUTER_PACKAGE_TYPE_ID" NUMBER, 
	"PRIMARY_MANF_ITEM_ID" NUMBER, 
	"FORMULARY_STATUS_CD" NUMBER(4,0), 
	"MEDICATION_ID" NUMBER, 
	"IS_ACTIVE" NUMBER(1,0), 
	"UPDATE_COUNT" NUMBER(4,0), 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
