--------------------------------------------------------
--  DDL for Table PHR_MEDICATION_ALERTS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."PHR_MEDICATION_ALERTS" 
   (	"MEDICATION_ID" NUMBER, 
	"ORDER_ALERT_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
