--------------------------------------------------------
--  DDL for Table PHR_ORDER_ALERTS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."PHR_ORDER_ALERTS" 
   (	"ACTIVE_DATE_TM" DATE, 
	"ACTION_TEXT_ID" NUMBER(4,0), 
	"ACTIVE_IND" NUMBER(2,0), 
	"ACTIVE_TYPE_CD" NUMBER(4,0), 
	"ALERT_CD" NUMBER(4,0), 
	"ALERT_TYPE_CD" NUMBER(4,0), 
	"BEGIN_EFFECTIVE_DATE_TM" DATE, 
	"END_EFFECTIVE_DATE_TM" DATE, 
	"INACTIVE_DATE_TM" DATE, 
	"UPDT_CNT" NUMBER(4,0), 
	"VIEW_ONLY_IND" NUMBER(4,0), 
	"CREATED_BY" NUMBER(4,0), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER(4,0), 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
