--------------------------------------------------------
--  DDL for Table PHR_DISPENSE_LOGS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."PHR_DISPENSE_LOGS" 
   (	"DISPENSE_HX_ID" NUMBER(4,0), 
	"ORDER_ID" NUMBER(4,0), 
	"ACTION_SEQUENCE" NUMBER(4,0), 
	"DISP_EVENT_TYPE_CD" NUMBER(4,0), 
	"REASON_CD" NUMBER(4,0), 
	"FILL_HX_ID" NUMBER(4,0), 
	"DOSES" FLOAT(8), 
	"EVENT_TOTAL_PRICE" FLOAT(8), 
	"RUN_USER_ID" NUMBER(4,0), 
	"UPDT_CNT" NUMBER(4,0), 
	"DISP_PRIORITY_CD" NUMBER(4,0), 
	"DISP_QTY" FLOAT(8), 
	"PHARM_TYPE_CD" NUMBER(4,0), 
	"DISP_QTY_UNIT_CD" FLOAT(8), 
	"DISP_LOC_CD" NUMBER(4,0), 
	"NEXT_DISPENSE_TZ" NUMBER(4,0), 
	"PREV_DISPENSE_TZ" NUMBER(4,0), 
	"DISPENSE_TZ" NUMBER(4,0), 
	"DISP_PRIORITY_TZ" NUMBER(4,0), 
	"FIRST_DOSE_TZ" NUMBER(4,0), 
	"NEXT_DISPENSE_DATE_TM" DATE, 
	"PREV_DISPENSE_DATE_TM" DATE, 
	"DISPENSE_DATE_TM" DATE, 
	"DISP_PRIORITY_DATE_TM" DATE, 
	"CHARGE_DATE_TM" DATE, 
	"FIRST_DOSE_TIME" DATE, 
	"FUTURE_CHARGE_IND" NUMBER(4,0), 
	"CREATED_BY" NUMBER(4,0), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER(4,0), 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
