--------------------------------------------------------
--  DDL for Table PHR_WORKFLOW_ACTIONS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."PHR_WORKFLOW_ACTIONS" 
   (	"WORKFLOW_EVENT_ID" NUMBER(4,0), 
	"DISPENSE_FROM_LOC_CD" NUMBER(4,0), 
	"WORKFLOW_CD" NUMBER(4,0), 
	"WORKFLOW_STS_CD" NUMBER(4,0), 
	"DISPENSE_CATEGORY_S" VARCHAR2(40 BYTE), 
	"DISPENSE_HX_ID" NUMBER(4,0), 
	"CREATED_DATE_TM" DATE, 
	"CREATED_TZ" NUMBER(4,0), 
	"SCHED_DATE_TM" DATE, 
	"SCHED_TZ" NUMBER(4,0), 
	"CMPLT_DATE_TM" DATE, 
	"CMPLT_TZ" NUMBER(4,0), 
	"PHARM_TYPE_CD" NUMBER(4,0), 
	"ITEM_ID" NUMBER(4,0), 
	"TOTAL_DOSE_NBR" NUMBER(4,0), 
	"UPDT_CNT" NUMBER(4,0), 
	"UPDT_TZ" NUMBER(4,0), 
	"CREATED_BY" NUMBER(4,0), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER(4,0), 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
