--------------------------------------------------------
--  DDL for Table PHR_SIG_CODE
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."PHR_SIG_CODE" 
   (	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"LANGUAGE_CD" NUMBER(4,0), 
	"SIG_CD" NUMBER(4,0), 
	"SIG_TYPE_CD" NUMBER(4,0), 
	"UPDT_CNT" NUMBER(4,0), 
	"VALUE" NUMBER(4,0), 
	"CREATED_BY" NUMBER(4,0), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER(4,0), 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
