--------------------------------------------------------
--  DDL for Table PHR_MEDICATION_DETAILS
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."PHR_MEDICATION_DETAILS" 
   (	"ID" NUMBER, 
	"DOSE_DESC" VARCHAR2(255 CHAR), 
	"ROUTE_CD" NUMBER, 
	"FREQUENCY_CD" NUMBER, 
	"PRN_IND" NUMBER(4,0), 
	"INFUSE_OVER" FLOAT(8), 
	"INFUSE_OVER_CD" NUMBER, 
	"DURATION" FLOAT(8), 
	"DURATION_UNIT_CD" NUMBER, 
	"STOP_TYPE_CD" NUMBER, 
	"NOTE_ID" NUMBER, 
	"NOTE_TYPE_CD" NUMBER(4,0), 
	"ADD_NOTE_ID" NUMBER, 
	"ADD_NOTE_TYPE_CD" NUMBER(4,0), 
	"NBR_LABELS" NUMBER(4,0), 
	"RX_QTY" FLOAT(8), 
	"DAW_CD" NUMBER, 
	"SIG_CODES" VARCHAR2(255 CHAR), 
	"PRN_REASON_CD" NUMBER, 
	"ORD_AS_SYNONYM_ID" NUMBER, 
	"RATE_NBR" FLOAT(8), 
	"RATE_UNIT_CD" NUMBER, 
	"RATE_DESC" VARCHAR2(100 CHAR), 
	"MEDICATION_ID" NUMBER, 
	"IS_ACTIVE" NUMBER(1,0), 
	"UPDATE_COUNT" NUMBER(4,0), 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
