--------------------------------------------------------
--  DDL for Table PHR_FILL_BATCH_LOG
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."PHR_FILL_BATCH_LOG" 
   (	"FILL_HX_ID" NUMBER(4,0), 
	"FILL_AUDIT_FLAG" NUMBER(2,0), 
	"FILL_BATCH_CD" NUMBER(4,0), 
	"FILL_TIME" NUMBER(4,0), 
	"FILL_UNIT_FLAG" NUMBER(2,0), 
	"SUSPEND_TIME" NUMBER(4,0), 
	"MAX_FILL_TIME" NUMBER(4,0), 
	"MAX_FILL_UNIT_FLAG" NUMBER(2,0), 
	"MAX_CYCLE_TIME" NUMBER(4,0), 
	"MAX_CYCLE_UNIT_FLAG" NUMBER(2,0), 
	"OUTPUT_FORMAT_CD" NUMBER(4,0), 
	"OUTPUT_DEVICE_CD" NUMBER(4,0), 
	"OUTPUT_DEVICE_S" VARCHAR2(50 BYTE), 
	"RUN_USER_ID" NUMBER(4,0), 
	"RUN_USER_S" VARCHAR2(50 BYTE), 
	"UPDT_CNT" NUMBER(4,0), 
	"START_DATE_TM" DATE, 
	"END_DATE_TM" DATE, 
	"FILL_DATE_TM" DATE, 
	"DIS_DATE_TM" DATE, 
	"PRINT_DATE_TM" DATE, 
	"ORDER_COUNT" NUMBER(4,0), 
	"FROM_DATE_TM" DATE, 
	"TO_DATE_TM" DATE, 
	"LOCATION_CD" NUMBER(4,0), 
	"FROM_TZ" NUMBER(4,0), 
	"TO_TZ" NUMBER(4,0), 
	"START_TZ" NUMBER(4,0), 
	"CREATED_BY" NUMBER(4,0), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER(4,0), 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
