--------------------------------------------------------
--  DDL for Table PHR_DISPENSE
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."PHR_DISPENSE" 
   (	"ID" NUMBER, 
	"MEDICATION_ID" NUMBER, 
	"ALWAYS_DISPENSE_FROM_FLAG" NUMBER(4,0), 
	"STRENGTH" FLOAT(8), 
	"STRENGTH_UNIT_CD" NUMBER(4,0), 
	"VOLUME" FLOAT(8), 
	"VOLUME_UNIT_CD" NUMBER(4,0), 
	"DISPENSE_FACTOR" FLOAT(8), 
	"PAT_ORDERABLE_IND" NUMBER(2,0), 
	"LEGAL_STATUS_CD" NUMBER(4,0), 
	"FORMULARY_STATUS_CD" NUMBER(4,0), 
	"PHARMACY_TYPE_CD" NUMBER(4,0), 
	"OE_FORMAT_FLAG" NUMBER(4,0), 
	"MED_FILTER_IND" NUMBER(2,0), 
	"CONTINUOUS_FILTER_IND" NUMBER(2,0), 
	"INTERMITTENT_FILTER_IND" NUMBER(2,0), 
	"DIVISIBLE_IND" NUMBER(2,0), 
	"USED_AS_BASE_IND" NUMBER(2,0), 
	"DISPENSE_QTY" FLOAT(8), 
	"INFINITE_DIV_IND" NUMBER(4,0), 
	"REUSABLE_IND" NUMBER(4,0), 
	"BASE_ISSUE_FACTOR" FLOAT(8), 
	"TPN_FILTER_IND" NUMBER(4,0), 
	"PKG_QTY_PER_PKG" FLOAT(8), 
	"TRACKING_TYPE_CD" NUMBER(4,0), 
	"COMPOUND_TEXT_ID" NUMBER, 
	"UPDATE_COUNT" NUMBER(4,0), 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER, 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
