--------------------------------------------------------
--  DDL for Table PHR_FILL_BATCH
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."PHR_FILL_BATCH" 
   (	"FILL_BATCH_CD" NUMBER(4,0), 
	"CYCLE_TIME" NUMBER(4,0), 
	"CYCLE_UNIT_FLAG" NUMBER(2,0), 
	"DISCONTINUE_TIME" NUMBER(4,0), 
	"DISCONTINUE_UNIT_FLAG" NUMBER(2,0), 
	"MAX_CYCLE_TIME" NUMBER(4,0), 
	"MAX_CYCLE_UNIT_FLAG" NUMBER(2,0), 
	"OUTPUT_FORMAT_CD" NUMBER(4,0), 
	"DEFAULT_PRINTER_CD" NUMBER(4,0), 
	"ORDER_TYPE_FLAG" NUMBER(2,0), 
	"LOCATION_CD" NUMBER(4,0), 
	"LOC_FACILITY_CD" NUMBER(4,0), 
	"CREATED_BY" NUMBER(4,0), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER(4,0), 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
