--------------------------------------------------------
--  DDL for Table PHR_PACKAGE_TYPE
--------------------------------------------------------

  CREATE TABLE "HISRHAMZEH"."PHR_PACKAGE_TYPE" 
   (	"ACTIVE_IND" NUMBER(4,0), 
	"ITEM_ID" NUMBER, 
	"PACKAGE_TYPE_ID" NUMBER, 
	"DESCRIPTION_P" VARCHAR2(100 BYTE), 
	"DESCRIPTION_S" VARCHAR2(100 BYTE), 
	"UPDT_CNT" NUMBER(4,0), 
	"CREATED_BY" NUMBER(4,0), 
	"CREATED_DATE" DATE, 
	"MODIFIED_BY" NUMBER(4,0), 
	"MODIFIED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
